import { network } from "hardhat";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/** LOCAL ONLY — versioned 1Q Phase 10B path. It requires an explicit token-independent Legion manifest. */
async function main() {
  const rootPath=resolve(process.env.ABCD_1Q_ROOT_MANIFEST_PATH||"deployments.abcd-1q-local.json"), legionPath=resolve(process.env.LEGION_NFT_V2_1Q_MANIFEST_PATH||""); if(!existsSync(rootPath)||!process.env.LEGION_NFT_V2_1Q_MANIFEST_PATH||!existsSync(legionPath)) throw new Error("Explicit 1Q root and Legion manifest paths are required.");
  const root=JSON.parse(readFileSync(rootPath,"utf8")), legionManifest=JSON.parse(readFileSync(legionPath,"utf8")); if(root.model!=="OWNER_APPROVED_1Q_SEVEN_ALLOCATION"||Number(root.chainId)!==31337||Number(legionManifest.chainId)!==31337) throw new Error("Invalid 1Q root or Legion manifest identity.");
  const {ethers}=await network.connect(); if(Number((await ethers.provider.getNetwork()).chainId)!==31337) throw new Error("1Q Phase 10B requires local 31337."); const tokenAddress=root.contracts?.ABCDTokenV2?.address, legionAddress=legionManifest.contracts?.LegionNFTV2?.address; if(!tokenAddress||!legionAddress||await ethers.provider.getCode(tokenAddress)==="0x"||await ethers.provider.getCode(legionAddress)==="0x") throw new Error("Live ABCDTokenV2 and LegionNFTV2 bytecode are required.");
  const token=await ethers.getContractAt("ABCDTokenV2",tokenAddress); await token.maxSupply(); const legion=await ethers.getContractAt("LegionNFTV2",legionAddress); const [admin,,,settlementAdmin,pauser]=await ethers.getSigners(); const adapter=await (await ethers.getContractFactory("LegionMarketplaceSettlementAdapterV2")).deploy(legionAddress,tokenAddress,admin.address,settlementAdmin.address,pauser.address); await adapter.waitForDeployment(); const role=await legion.LEGION_MARKETPLACE_SETTLER_ROLE(); const legionAdmin= (await ethers.getSigners()).find(s=>s.address.toLowerCase()===(legionManifest.roles?.legionAdmin||legionManifest.roles?.defaultAdmin).toLowerCase()); if(!legionAdmin) throw new Error("Legion admin signer unavailable."); const grant=await legion.connect(legionAdmin).grantRole(role,await adapter.getAddress()); const receipt=await grant.wait(); if(!receipt||receipt.status!==1||!await legion.hasRole(role,await adapter.getAddress())) throw new Error("Settlement role grant failed."); if((await adapter.abcdToken()).toLowerCase()!==tokenAddress.toLowerCase()) throw new Error("Phase 10B token binding mismatch."); const block=await ethers.provider.getBlock(receipt.blockNumber); const output=resolve(process.env.LEGION_MARKETPLACE_1Q_MANIFEST_PATH||"deployments.legion-marketplace-10b-1q-local.json"); const manifest={schemaVersion:"1.0",identity:"1Q CANONICAL CANDIDATE — LOCAL ONLY",model:"OWNER_APPROVED_1Q_PHASE10B",chainId:31337,rpcUrl:process.env.ABCDEFI_LOCAL_RPC_URL||"http://127.0.0.1:8545",rootDeploymentVersion:root.deploymentVersion,legionDeploymentVersion:legionManifest.deploymentVersion,deploymentVersion:`legion-marketplace-10b-1q-local-${block?.hash}`,deploymentBlock:receipt.blockNumber,deploymentTimestamp:block?.timestamp,contracts:{ABCDTokenV2:{address:tokenAddress},LegionNFTV2:{address:legionAddress},LegionMarketplaceSettlementAdapterV2:{address:await adapter.getAddress(),settlementRoleGrantTransaction:grant.hash}},roles:{defaultAdmin:admin.address,settlementAdmin:settlementAdmin.address,pauser:pauser.address}};writeFileSync(output,JSON.stringify(manifest,null,2)+"\n");console.log(JSON.stringify({output,...manifest},null,2));
}
void main();
