/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ABCDeFiGovernor } from './ABCDeFiGovernor.js';
export type { IERC20Votes } from './IERC20Votes.js';