const { Contract, Interface } = require('ethers');
const { projectionRuntimeFields, checkpointRuntimeFields, checkpointRuntimeMatches } = require('../../config/projectionRuntimeContext.cjs');
const lower = (value) => typeof value === 'string' ? value.toLowerCase() : value;
const value = (input, item) => typeof item === 'bigint' ? item.toString() : input.type === 'address' ? lower(item) : item;
class IcoV3Indexer {
  constructor({ manifest, artifact, provider, models }) { this.manifest = manifest; this.provider = provider; this.models = models; this.iface = new Interface(artifact.abi); this.topics = artifact.abi.filter((item) => item.type === 'event').map((item) => this.iface.getEvent(item.name).topicHash); this.contract = new Contract(manifest.address, artifact.abi, provider); }
  identity() { return { chainId: String(this.manifest.chainId), deploymentVersion: this.manifest.deploymentVersion, ...projectionRuntimeFields(this.manifest), icoAddress: this.manifest.address }; }
  async assertDeployment() { const [network, code, token] = await Promise.all([this.provider.getNetwork(), this.provider.getCode(this.manifest.address), this.contract.abcd()]); if (Number(network.chainId) !== Number(this.manifest.chainId) || code === '0x' || lower(token) !== this.manifest.abcdAddress) throw new Error('ICOManagerV3 canonical deployment, chain, or ABCDTokenV2 binding is invalid.'); }
  async syncOnce() { await this.assertDeployment(); const runtime = await checkpointRuntimeFields(this.manifest, this.provider, [this.manifest.address, this.manifest.abcdAddress]); const identity = this.identity(); const checkpoint = await this.models.IcoV3Checkpoint.findOne(identity).lean(); if (checkpoint && !checkpointRuntimeMatches(checkpoint, runtime)) throw new Error('ICO V3 checkpoint runtime identity does not match the active canonical deployment.'); if (checkpoint?.lastProcessedBlock) { const block = await this.provider.getBlock(Number(checkpoint.lastProcessedBlock)); if (!block || lower(block.hash) !== lower(checkpoint.lastProcessedBlockHash)) throw new Error('ICO V3 checkpoint does not match the active canonical chain.'); }
    const latest = await this.provider.getBlockNumber(); const from = checkpoint?.lastProcessedBlock ? Number(checkpoint.lastProcessedBlock) + 1 : this.manifest.deploymentBlock; if (latest < from) return { checkpoint: checkpoint?.lastProcessedBlock || null, processed: 0 };
    const logs = await this.provider.getLogs({ address: this.manifest.address, topics: [this.topics], fromBlock: from, toBlock: latest }); logs.sort((a, b) => Number(a.blockNumber) - Number(b.blockNumber) || Number(a.index ?? a.logIndex) - Number(b.index ?? b.logIndex));
    for (const log of logs) { const parsed = this.iface.parseLog({ topics: log.topics, data: log.data }); if (!parsed) continue; const args = Object.fromEntries(parsed.fragment.inputs.map((input, index) => [input.name || String(index), value(input, parsed.args[index])])); const event = { ...identity, transactionHash: lower(log.transactionHash), blockNumber: String(log.blockNumber), logIndex: Number(log.index ?? log.logIndex), blockHash: lower(log.blockHash), eventName: parsed.name, args, indexedAt: new Date() }; await this.models.IcoV3Event.updateOne({ ...identity, transactionHash: event.transactionHash, logIndex: event.logIndex }, { $setOnInsert: event }, { upsert: true }); }
    const block = await this.provider.getBlock(latest); await this.models.IcoV3Checkpoint.updateOne(identity, { $set: { ...identity, ...runtime, lastProcessedBlock: String(latest), lastProcessedBlockHash: lower(block.hash), indexedAt: new Date() } }, { upsert: true }); return { checkpoint: String(latest), processed: logs.length };
  }
}
module.exports = { IcoV3Indexer };
