/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IPresale {
      
    export type BuyerInfoStruct = {ethContributed: BigNumberish, tokensPurchased: BigNumberish, claimed: boolean}

    export type BuyerInfoStructOutput = [ethContributed: bigint, tokensPurchased: bigint, claimed: boolean] & {ethContributed: bigint, tokensPurchased: bigint, claimed: boolean }
  
    }

  export interface IPresaleInterface extends Interface {
    getFunction(nameOrSignature: "buyWithETH" | "cancelPresale" | "claimTokens" | "finalizePresale" | "getBuyerInfo" | "getState" | "setWhitelist" | "startPresale" | "withdrawProceeds"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PresaleFinalized" | "PresaleStateChanged" | "TokensClaimed" | "TokensPurchased" | "WhitelistUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'buyWithETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelPresale', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizePresale', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBuyerInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getState', values?: undefined): string;
encodeFunctionData(functionFragment: 'setWhitelist', values: [AddressLike[], boolean]): string;
encodeFunctionData(functionFragment: 'startPresale', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawProceeds', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buyWithETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelPresale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizePresale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBuyerInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startPresale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawProceeds', data: BytesLike): Result;
  }

  
    export namespace PresaleFinalizedEvent {
      export type InputTuple = [totalEthRaised: BigNumberish, totalTokensSold: BigNumberish];
      export type OutputTuple = [totalEthRaised: bigint, totalTokensSold: bigint];
      export interface OutputObject {totalEthRaised: bigint, totalTokensSold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PresaleStateChangedEvent {
      export type InputTuple = [newState: BigNumberish];
      export type OutputTuple = [newState: bigint];
      export interface OutputObject {newState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensClaimedEvent {
      export type InputTuple = [buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [buyer: string, amount: bigint];
      export interface OutputObject {buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, ethSpent: BigNumberish, tokensBought: BigNumberish];
      export type OutputTuple = [buyer: string, ethSpent: bigint, tokensBought: bigint];
      export interface OutputObject {buyer: string, ethSpent: bigint, tokensBought: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WhitelistUpdatedEvent {
      export type InputTuple = [account: AddressLike, isWhitelisted: boolean];
      export type OutputTuple = [account: string, isWhitelisted: boolean];
      export interface OutputObject {account: string, isWhitelisted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IPresale extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPresale;
    waitForDeployment(): Promise<this>;

    interface: IPresaleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buyWithETH: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    cancelPresale: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimTokens: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    finalizePresale: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getBuyerInfo: TypedContractMethod<
      [buyer: AddressLike, ],
      [IPresale.BuyerInfoStructOutput],
      'view'
    >
    

    
    getState: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setWhitelist: TypedContractMethod<
      [accounts: AddressLike[], status: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    startPresale: TypedContractMethod<
      [startTime: BigNumberish, endTime: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawProceeds: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buyWithETH'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelPresale'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimTokens'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizePresale'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBuyerInfo'): TypedContractMethod<
      [buyer: AddressLike, ],
      [IPresale.BuyerInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getState'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setWhitelist'): TypedContractMethod<
      [accounts: AddressLike[], status: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startPresale'): TypedContractMethod<
      [startTime: BigNumberish, endTime: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawProceeds'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PresaleFinalized'): TypedContractEvent<PresaleFinalizedEvent.InputTuple, PresaleFinalizedEvent.OutputTuple, PresaleFinalizedEvent.OutputObject>;
getEvent(key: 'PresaleStateChanged'): TypedContractEvent<PresaleStateChangedEvent.InputTuple, PresaleStateChangedEvent.OutputTuple, PresaleStateChangedEvent.OutputObject>;
getEvent(key: 'TokensClaimed'): TypedContractEvent<TokensClaimedEvent.InputTuple, TokensClaimedEvent.OutputTuple, TokensClaimedEvent.OutputObject>;
getEvent(key: 'TokensPurchased'): TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
getEvent(key: 'WhitelistUpdated'): TypedContractEvent<WhitelistUpdatedEvent.InputTuple, WhitelistUpdatedEvent.OutputTuple, WhitelistUpdatedEvent.OutputObject>;

    filters: {
      
      'PresaleFinalized(uint256,uint256)': TypedContractEvent<PresaleFinalizedEvent.InputTuple, PresaleFinalizedEvent.OutputTuple, PresaleFinalizedEvent.OutputObject>;
      PresaleFinalized: TypedContractEvent<PresaleFinalizedEvent.InputTuple, PresaleFinalizedEvent.OutputTuple, PresaleFinalizedEvent.OutputObject>;
    

      'PresaleStateChanged(uint8)': TypedContractEvent<PresaleStateChangedEvent.InputTuple, PresaleStateChangedEvent.OutputTuple, PresaleStateChangedEvent.OutputObject>;
      PresaleStateChanged: TypedContractEvent<PresaleStateChangedEvent.InputTuple, PresaleStateChangedEvent.OutputTuple, PresaleStateChangedEvent.OutputObject>;
    

      'TokensClaimed(address,uint256)': TypedContractEvent<TokensClaimedEvent.InputTuple, TokensClaimedEvent.OutputTuple, TokensClaimedEvent.OutputObject>;
      TokensClaimed: TypedContractEvent<TokensClaimedEvent.InputTuple, TokensClaimedEvent.OutputTuple, TokensClaimedEvent.OutputObject>;
    

      'TokensPurchased(address,uint256,uint256)': TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
      TokensPurchased: TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
    

      'WhitelistUpdated(address,bool)': TypedContractEvent<WhitelistUpdatedEvent.InputTuple, WhitelistUpdatedEvent.OutputTuple, WhitelistUpdatedEvent.OutputObject>;
      WhitelistUpdated: TypedContractEvent<WhitelistUpdatedEvent.InputTuple, WhitelistUpdatedEvent.OutputTuple, WhitelistUpdatedEvent.OutputObject>;
    
    };
  }