/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAggregatorV3V2 } from './IAggregatorV3V2.js';
export type { OracleAdapterV2 } from './OracleAdapterV2.js';