/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace FranchiseRegistryV2 {
      
    export type ApplicationStruct = {applicant: AddressLike, legionTokenId: BigNumberish, metadataURI: string, status: BigNumberish, exists: boolean}

    export type ApplicationStructOutput = [applicant: string, legionTokenId: bigint, metadataURI: string, status: bigint, exists: boolean] & {applicant: string, legionTokenId: bigint, metadataURI: string, status: bigint, exists: boolean }
  

    export type FranchiseRecordStruct = {legionContract: AddressLike, legionTokenId: BigNumberish, operator: AddressLike, status: BigNumberish, operatorVersion: BigNumberish, metadataURI: string, exists: boolean}

    export type FranchiseRecordStructOutput = [legionContract: string, legionTokenId: bigint, operator: string, status: bigint, operatorVersion: bigint, metadataURI: string, exists: boolean] & {legionContract: string, legionTokenId: bigint, operator: string, status: bigint, operatorVersion: bigint, metadataURI: string, exists: boolean }
  

    export type TransferRequestStruct = {tokenId: BigNumberish, currentOperator: AddressLike, proposedOperator: AddressLike, operatorVersion: BigNumberish, active: boolean, approved: boolean}

    export type TransferRequestStructOutput = [tokenId: bigint, currentOperator: string, proposedOperator: string, operatorVersion: bigint, active: boolean, approved: boolean] & {tokenId: bigint, currentOperator: string, proposedOperator: string, operatorVersion: bigint, active: boolean, approved: boolean }
  
    }

  export interface FranchiseRegistryV2Interface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "FRANCHISE_ADMIN_ROLE" | "FRANCHISE_MINTER_ROLE" | "FRANCHISE_TRANSFER_APPROVER_ROLE" | "PAUSER_ROLE" | "activeApplicationForLegionToken" | "activeFranchiseForLegionToken" | "activeTransferRequestForToken" | "approveApplication" | "approveTransfer" | "cancelApplication" | "cancelTransfer" | "executeTransfer" | "franchiseNFT" | "getApplication" | "getFranchise" | "getRoleAdmin" | "getTransferRequest" | "grantRole" | "hasRole" | "invalidateTransfer" | "legionNFT" | "mintApprovedApplication" | "pause" | "paused" | "reactivate" | "rejectApplication" | "renounceRole" | "requestTransfer" | "revoke" | "revokeRole" | "submitApplication" | "supportsInterface" | "suspend" | "unpause" | "updateMetadata"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FranchiseApplicationApproved" | "FranchiseApplicationCancelled" | "FranchiseApplicationRejected" | "FranchiseApplicationSubmitted" | "FranchiseMetadataUpdated" | "FranchiseMinted" | "FranchiseStatusChanged" | "FranchiseTransferApproved" | "FranchiseTransferCancelled" | "FranchiseTransferRequested" | "FranchiseTransferred" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FRANCHISE_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FRANCHISE_MINTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FRANCHISE_TRANSFER_APPROVER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeApplicationForLegionToken', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'activeFranchiseForLegionToken', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'activeTransferRequestForToken', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveApplication', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelApplication', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'executeTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'franchiseNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApplication', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getFranchise', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTransferRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'invalidateTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'legionNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'mintApprovedApplication', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'reactivate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'rejectApplication', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestTransfer', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'revoke', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'submitApplication', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'suspend', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateMetadata', values: [BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FRANCHISE_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FRANCHISE_MINTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FRANCHISE_TRANSFER_APPROVER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeApplicationForLegionToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeFranchiseForLegionToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeTransferRequestForToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveApplication', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelApplication', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'franchiseNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApplication', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFranchise', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransferRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invalidateTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'legionNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintApprovedApplication', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reactivate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectApplication', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revoke', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitApplication', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'suspend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMetadata', data: BytesLike): Result;
  }

  
    export namespace FranchiseApplicationApprovedEvent {
      export type InputTuple = [applicationId: BigNumberish, administrator: AddressLike];
      export type OutputTuple = [applicationId: bigint, administrator: string];
      export interface OutputObject {applicationId: bigint, administrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseApplicationCancelledEvent {
      export type InputTuple = [applicationId: BigNumberish, applicant: AddressLike];
      export type OutputTuple = [applicationId: bigint, applicant: string];
      export interface OutputObject {applicationId: bigint, applicant: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseApplicationRejectedEvent {
      export type InputTuple = [applicationId: BigNumberish, administrator: AddressLike];
      export type OutputTuple = [applicationId: bigint, administrator: string];
      export interface OutputObject {applicationId: bigint, administrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseApplicationSubmittedEvent {
      export type InputTuple = [applicationId: BigNumberish, legionTokenId: BigNumberish, applicant: AddressLike, metadataURI: string];
      export type OutputTuple = [applicationId: bigint, legionTokenId: bigint, applicant: string, metadataURI: string];
      export interface OutputObject {applicationId: bigint, legionTokenId: bigint, applicant: string, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseMetadataUpdatedEvent {
      export type InputTuple = [tokenId: BigNumberish, previousMetadataURI: string, newMetadataURI: string, administrator: AddressLike];
      export type OutputTuple = [tokenId: bigint, previousMetadataURI: string, newMetadataURI: string, administrator: string];
      export interface OutputObject {tokenId: bigint, previousMetadataURI: string, newMetadataURI: string, administrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseMintedEvent {
      export type InputTuple = [tokenId: BigNumberish, applicationId: BigNumberish, owner: AddressLike, legionContract: AddressLike, legionTokenId: BigNumberish, metadataURI: string];
      export type OutputTuple = [tokenId: bigint, applicationId: bigint, owner: string, legionContract: string, legionTokenId: bigint, metadataURI: string];
      export interface OutputObject {tokenId: bigint, applicationId: bigint, owner: string, legionContract: string, legionTokenId: bigint, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseStatusChangedEvent {
      export type InputTuple = [tokenId: BigNumberish, previousStatus: BigNumberish, newStatus: BigNumberish, administrator: AddressLike];
      export type OutputTuple = [tokenId: bigint, previousStatus: bigint, newStatus: bigint, administrator: string];
      export interface OutputObject {tokenId: bigint, previousStatus: bigint, newStatus: bigint, administrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseTransferApprovedEvent {
      export type InputTuple = [requestId: BigNumberish, administrator: AddressLike];
      export type OutputTuple = [requestId: bigint, administrator: string];
      export interface OutputObject {requestId: bigint, administrator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseTransferCancelledEvent {
      export type InputTuple = [requestId: BigNumberish, cancelledBy: AddressLike, byAdministrator: boolean];
      export type OutputTuple = [requestId: bigint, cancelledBy: string, byAdministrator: boolean];
      export interface OutputObject {requestId: bigint, cancelledBy: string, byAdministrator: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseTransferRequestedEvent {
      export type InputTuple = [requestId: BigNumberish, tokenId: BigNumberish, currentOperator: AddressLike, proposedOperator: AddressLike, operatorVersion: BigNumberish];
      export type OutputTuple = [requestId: bigint, tokenId: bigint, currentOperator: string, proposedOperator: string, operatorVersion: bigint];
      export interface OutputObject {requestId: bigint, tokenId: bigint, currentOperator: string, proposedOperator: string, operatorVersion: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FranchiseTransferredEvent {
      export type InputTuple = [requestId: BigNumberish, tokenId: BigNumberish, previousOperator: AddressLike, newOperator: AddressLike, newOperatorVersion: BigNumberish];
      export type OutputTuple = [requestId: bigint, tokenId: bigint, previousOperator: string, newOperator: string, newOperatorVersion: bigint];
      export interface OutputObject {requestId: bigint, tokenId: bigint, previousOperator: string, newOperator: string, newOperatorVersion: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FranchiseRegistryV2 extends BaseContract {
    
    connect(runner?: ContractRunner | null): FranchiseRegistryV2;
    waitForDeployment(): Promise<this>;

    interface: FranchiseRegistryV2Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FRANCHISE_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FRANCHISE_MINTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FRANCHISE_TRANSFER_APPROVER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    activeApplicationForLegionToken: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    activeFranchiseForLegionToken: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    activeTransferRequestForToken: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    approveApplication: TypedContractMethod<
      [applicationId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    approveTransfer: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelApplication: TypedContractMethod<
      [applicationId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTransfer: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executeTransfer: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    franchiseNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getApplication: TypedContractMethod<
      [applicationId: BigNumberish, ],
      [FranchiseRegistryV2.ApplicationStructOutput],
      'view'
    >
    

    
    getFranchise: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [FranchiseRegistryV2.FranchiseRecordStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getTransferRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [FranchiseRegistryV2.TransferRequestStructOutput],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    invalidateTransfer: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    legionNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mintApprovedApplication: TypedContractMethod<
      [applicationId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    reactivate: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    rejectApplication: TypedContractMethod<
      [applicationId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestTransfer: TypedContractMethod<
      [tokenId: BigNumberish, proposedOperator: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    revoke: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitApplication: TypedContractMethod<
      [legionTokenId: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    suspend: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateMetadata: TypedContractMethod<
      [tokenId: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FRANCHISE_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FRANCHISE_MINTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FRANCHISE_TRANSFER_APPROVER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'activeApplicationForLegionToken'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeFranchiseForLegionToken'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activeTransferRequestForToken'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approveApplication'): TypedContractMethod<
      [applicationId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveTransfer'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelApplication'): TypedContractMethod<
      [applicationId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTransfer'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executeTransfer'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'franchiseNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getApplication'): TypedContractMethod<
      [applicationId: BigNumberish, ],
      [FranchiseRegistryV2.ApplicationStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getFranchise'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [FranchiseRegistryV2.FranchiseRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTransferRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [FranchiseRegistryV2.TransferRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'invalidateTransfer'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'legionNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mintApprovedApplication'): TypedContractMethod<
      [applicationId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'reactivate'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectApplication'): TypedContractMethod<
      [applicationId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestTransfer'): TypedContractMethod<
      [tokenId: BigNumberish, proposedOperator: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revoke'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitApplication'): TypedContractMethod<
      [legionTokenId: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'suspend'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMetadata'): TypedContractMethod<
      [tokenId: BigNumberish, metadataURI: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FranchiseApplicationApproved'): TypedContractEvent<FranchiseApplicationApprovedEvent.InputTuple, FranchiseApplicationApprovedEvent.OutputTuple, FranchiseApplicationApprovedEvent.OutputObject>;
getEvent(key: 'FranchiseApplicationCancelled'): TypedContractEvent<FranchiseApplicationCancelledEvent.InputTuple, FranchiseApplicationCancelledEvent.OutputTuple, FranchiseApplicationCancelledEvent.OutputObject>;
getEvent(key: 'FranchiseApplicationRejected'): TypedContractEvent<FranchiseApplicationRejectedEvent.InputTuple, FranchiseApplicationRejectedEvent.OutputTuple, FranchiseApplicationRejectedEvent.OutputObject>;
getEvent(key: 'FranchiseApplicationSubmitted'): TypedContractEvent<FranchiseApplicationSubmittedEvent.InputTuple, FranchiseApplicationSubmittedEvent.OutputTuple, FranchiseApplicationSubmittedEvent.OutputObject>;
getEvent(key: 'FranchiseMetadataUpdated'): TypedContractEvent<FranchiseMetadataUpdatedEvent.InputTuple, FranchiseMetadataUpdatedEvent.OutputTuple, FranchiseMetadataUpdatedEvent.OutputObject>;
getEvent(key: 'FranchiseMinted'): TypedContractEvent<FranchiseMintedEvent.InputTuple, FranchiseMintedEvent.OutputTuple, FranchiseMintedEvent.OutputObject>;
getEvent(key: 'FranchiseStatusChanged'): TypedContractEvent<FranchiseStatusChangedEvent.InputTuple, FranchiseStatusChangedEvent.OutputTuple, FranchiseStatusChangedEvent.OutputObject>;
getEvent(key: 'FranchiseTransferApproved'): TypedContractEvent<FranchiseTransferApprovedEvent.InputTuple, FranchiseTransferApprovedEvent.OutputTuple, FranchiseTransferApprovedEvent.OutputObject>;
getEvent(key: 'FranchiseTransferCancelled'): TypedContractEvent<FranchiseTransferCancelledEvent.InputTuple, FranchiseTransferCancelledEvent.OutputTuple, FranchiseTransferCancelledEvent.OutputObject>;
getEvent(key: 'FranchiseTransferRequested'): TypedContractEvent<FranchiseTransferRequestedEvent.InputTuple, FranchiseTransferRequestedEvent.OutputTuple, FranchiseTransferRequestedEvent.OutputObject>;
getEvent(key: 'FranchiseTransferred'): TypedContractEvent<FranchiseTransferredEvent.InputTuple, FranchiseTransferredEvent.OutputTuple, FranchiseTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'FranchiseApplicationApproved(uint256,address)': TypedContractEvent<FranchiseApplicationApprovedEvent.InputTuple, FranchiseApplicationApprovedEvent.OutputTuple, FranchiseApplicationApprovedEvent.OutputObject>;
      FranchiseApplicationApproved: TypedContractEvent<FranchiseApplicationApprovedEvent.InputTuple, FranchiseApplicationApprovedEvent.OutputTuple, FranchiseApplicationApprovedEvent.OutputObject>;
    

      'FranchiseApplicationCancelled(uint256,address)': TypedContractEvent<FranchiseApplicationCancelledEvent.InputTuple, FranchiseApplicationCancelledEvent.OutputTuple, FranchiseApplicationCancelledEvent.OutputObject>;
      FranchiseApplicationCancelled: TypedContractEvent<FranchiseApplicationCancelledEvent.InputTuple, FranchiseApplicationCancelledEvent.OutputTuple, FranchiseApplicationCancelledEvent.OutputObject>;
    

      'FranchiseApplicationRejected(uint256,address)': TypedContractEvent<FranchiseApplicationRejectedEvent.InputTuple, FranchiseApplicationRejectedEvent.OutputTuple, FranchiseApplicationRejectedEvent.OutputObject>;
      FranchiseApplicationRejected: TypedContractEvent<FranchiseApplicationRejectedEvent.InputTuple, FranchiseApplicationRejectedEvent.OutputTuple, FranchiseApplicationRejectedEvent.OutputObject>;
    

      'FranchiseApplicationSubmitted(uint256,uint256,address,string)': TypedContractEvent<FranchiseApplicationSubmittedEvent.InputTuple, FranchiseApplicationSubmittedEvent.OutputTuple, FranchiseApplicationSubmittedEvent.OutputObject>;
      FranchiseApplicationSubmitted: TypedContractEvent<FranchiseApplicationSubmittedEvent.InputTuple, FranchiseApplicationSubmittedEvent.OutputTuple, FranchiseApplicationSubmittedEvent.OutputObject>;
    

      'FranchiseMetadataUpdated(uint256,string,string,address)': TypedContractEvent<FranchiseMetadataUpdatedEvent.InputTuple, FranchiseMetadataUpdatedEvent.OutputTuple, FranchiseMetadataUpdatedEvent.OutputObject>;
      FranchiseMetadataUpdated: TypedContractEvent<FranchiseMetadataUpdatedEvent.InputTuple, FranchiseMetadataUpdatedEvent.OutputTuple, FranchiseMetadataUpdatedEvent.OutputObject>;
    

      'FranchiseMinted(uint256,uint256,address,address,uint256,string)': TypedContractEvent<FranchiseMintedEvent.InputTuple, FranchiseMintedEvent.OutputTuple, FranchiseMintedEvent.OutputObject>;
      FranchiseMinted: TypedContractEvent<FranchiseMintedEvent.InputTuple, FranchiseMintedEvent.OutputTuple, FranchiseMintedEvent.OutputObject>;
    

      'FranchiseStatusChanged(uint256,uint8,uint8,address)': TypedContractEvent<FranchiseStatusChangedEvent.InputTuple, FranchiseStatusChangedEvent.OutputTuple, FranchiseStatusChangedEvent.OutputObject>;
      FranchiseStatusChanged: TypedContractEvent<FranchiseStatusChangedEvent.InputTuple, FranchiseStatusChangedEvent.OutputTuple, FranchiseStatusChangedEvent.OutputObject>;
    

      'FranchiseTransferApproved(uint256,address)': TypedContractEvent<FranchiseTransferApprovedEvent.InputTuple, FranchiseTransferApprovedEvent.OutputTuple, FranchiseTransferApprovedEvent.OutputObject>;
      FranchiseTransferApproved: TypedContractEvent<FranchiseTransferApprovedEvent.InputTuple, FranchiseTransferApprovedEvent.OutputTuple, FranchiseTransferApprovedEvent.OutputObject>;
    

      'FranchiseTransferCancelled(uint256,address,bool)': TypedContractEvent<FranchiseTransferCancelledEvent.InputTuple, FranchiseTransferCancelledEvent.OutputTuple, FranchiseTransferCancelledEvent.OutputObject>;
      FranchiseTransferCancelled: TypedContractEvent<FranchiseTransferCancelledEvent.InputTuple, FranchiseTransferCancelledEvent.OutputTuple, FranchiseTransferCancelledEvent.OutputObject>;
    

      'FranchiseTransferRequested(uint256,uint256,address,address,uint64)': TypedContractEvent<FranchiseTransferRequestedEvent.InputTuple, FranchiseTransferRequestedEvent.OutputTuple, FranchiseTransferRequestedEvent.OutputObject>;
      FranchiseTransferRequested: TypedContractEvent<FranchiseTransferRequestedEvent.InputTuple, FranchiseTransferRequestedEvent.OutputTuple, FranchiseTransferRequestedEvent.OutputObject>;
    

      'FranchiseTransferred(uint256,uint256,address,address,uint64)': TypedContractEvent<FranchiseTransferredEvent.InputTuple, FranchiseTransferredEvent.OutputTuple, FranchiseTransferredEvent.OutputObject>;
      FranchiseTransferred: TypedContractEvent<FranchiseTransferredEvent.InputTuple, FranchiseTransferredEvent.OutputTuple, FranchiseTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }