const test = require('node:test'); const assert = require('node:assert/strict'); const { createIcoV2Controller, claimability } = require('../modules/icoV2/icoV2.controller.cjs');
const address = '0x1000000000000000000000000000000000000001'; const buyer = '0x2000000000000000000000000000000000000002'; const otherBuyer = '0x3000000000000000000000000000000000000003'; const hash = `0x${'a'.repeat(64)}`; const manifest = { chainId: 31337, deploymentVersion: 'ico-v2-test', address, rpcUrl: 'http://example.invalid' };
function response() { return { statusCode: 200, body: null, status(code) { this.statusCode = code; return this; }, json(value) { this.body = value; return this; } }; }
function eventsQuery(records, filter) { const selected = records.filter((event) => Object.entries(filter).every(([key, value]) => key === 'args.buyer' ? event.args.buyer === value : event[key] === value)); return { sort() { return { lean: async () => selected.slice().sort((a, b) => Number(a.blockNumber) - Number(b.blockNumber) || a.logIndex - b.logIndex) }; } }; }
function dependencies({ checkpoint = { chainId: '31337', deploymentVersion: 'ico-v2-test', icoAddress: address, lastProcessedBlock: '9', lastProcessedBlockHash: hash }, latest = 9, records = [], purchase = { allocation: 10n, bnbPaid: 11n, claimed: 0n, stageOneAllocation: 10n, stageTwoAllocation: 0n, refunded: false }, vestedTotal = 0n } = {}) { const models = { IcoV2Checkpoint: { findOne: () => ({ lean: async () => checkpoint }) }, IcoV2Event: { find: (filter) => eventsQuery(records, filter) } }; const provider = { getNetwork: async () => ({ chainId: 31337n }), getCode: async () => '0x1234', getBlock: async () => ({ hash }), getBlockNumber: async () => latest }; const contract = { lifecycle: async () => 1n, stage: async () => ({ startTime: 1n, endTime: 2n, inventory: 1000n, sold: 10n, priceUsdWad: 8000000000000000n }), totalAllocated: async () => 10n, totalBnbCollected: async () => 11n, totalBnbRefunded: async () => 0n, totalBnbWithdrawn: async () => 0n, tgeTimestamp: async () => 0n, currentStage: async () => 0n, paused: async () => false, bnbUsdFeed: async () => address, feedDecimals: async () => 8n, maxPriceAge: async () => 3600n, communityWallet: async () => buyer, proceedsRecipient: async () => otherBuyer, purchaseOf: async () => purchase, claimable: async () => vestedTotal, eligibleWallet: async () => true }; return { loadManifest: () => manifest, models, providerFactory: () => provider, contractFactory: () => contract }; }
test('ICO V2 read API fails closed when no canonical ICOManagerV2 manifest exists', async () => { const controller = createIcoV2Controller({ loadManifest: () => null }); const res = response(); await controller.status({}, res, (error) => { throw error; }); assert.equal(res.statusCode, 503); assert.equal(res.body.status, 'UNAVAILABLE'); assert.match(res.body.reason, /ICOManagerV2 has not been deployed/); assert.equal(res.body.source, 'canonical-ico-v2-on-chain'); });
test('ICO V2 status/history use only exact canonical events, deterministic ordering, buyer isolation, and aggregates', async () => { const base = { chainId: '31337', deploymentVersion: 'ico-v2-test', icoAddress: address }; const records = [{ ...base, eventName: 'IcoPurchase', blockNumber: '8', logIndex: 2, args: { buyer, allocation: '20', bnbPaid: '4' } }, { ...base, eventName: 'IcoRefundClaimed', blockNumber: '9', logIndex: 1, args: { buyer, allocationReversed: '5', bnbAmount: '1' } }, { ...base, eventName: 'IcoTokensClaimed', blockNumber: '9', logIndex: 3, args: { buyer, amount: '7' } }, { ...base, eventName: 'VestingCompleted', blockNumber: '9', logIndex: 4, args: { buyer } }, { ...base, eventName: 'IcoCancelled', blockNumber: '9', logIndex: 2, args: {} }, { ...base, deploymentVersion: 'other-deployment', eventName: 'IcoPurchase', blockNumber: '1', logIndex: 0, args: { buyer, allocation: '999' } }, { ...base, icoAddress: otherBuyer, eventName: 'IcoPurchase', blockNumber: '1', logIndex: 0, args: { buyer, allocation: '999' } }, { ...base, chainId: '1', eventName: 'IcoPurchase', blockNumber: '1', logIndex: 0, args: { buyer, allocation: '999' } }, { ...base, eventName: 'IcoPurchase', blockNumber: '8', logIndex: 1, args: { buyer: otherBuyer, allocation: '999' } }]; const controller = createIcoV2Controller(dependencies({ records })); const status = response(); const history = response(); const wallet = response(); await controller.status({}, status, (error) => { throw error; }); await controller.history({}, history, (error) => { throw error; }); await controller.buyer({ params: { address: buyer } }, wallet, (error) => { throw error; }); assert.equal(status.body.data.aggregates.purchasedAllocation, '1019'); assert.equal(status.body.data.aggregates.refundedAllocation, '5'); assert.equal(status.body.data.aggregates.claimedAbcd, '7'); assert.equal(status.body.data.aggregates.cancellations, 1); assert.deepEqual(history.body.data.events.map((event) => `${event.blockNumber}:${event.logIndex}`), ['8:1', '8:2', '9:1', '9:2', '9:3', '9:4']); assert.deepEqual(wallet.body.data.history.map((event) => event.args.buyer), [buyer, buyer, buyer, buyer]); });
test('ICO V2 API fails closed on stale or hash-mismatched checkpoints', async () => { for (const options of [{ latest: 10 }, { checkpoint: { chainId: '31337', deploymentVersion: 'ico-v2-test', icoAddress: address, lastProcessedBlock: '9', lastProcessedBlockHash: `0x${'b'.repeat(64)}` } }]) { const controller = createIcoV2Controller(dependencies(options)); const res = response(); await controller.status({}, res, (error) => { throw error; }); assert.equal(res.statusCode, 503); assert.match(res.body.reason, /checkpoint (is stale|does not match)/); } });
test('ICO V2 buyer reads distinguish cumulative vested entitlement from the amount claimable now', async () => {
  const purchase = { allocation: 100n, bnbPaid: 1n, claimed: 0n, stageOneAllocation: 0n, stageTwoAllocation: 100n, refunded: false };
  assert.deepEqual(claimability(purchase, 0n), { vestedTotal: 0n, claimableNow: 0n });
  assert.deepEqual(claimability(purchase, 25n), { vestedTotal: 25n, claimableNow: 25n });
  const partial = { ...purchase, claimed: 10n };
  assert.deepEqual(claimability(partial, 25n), { vestedTotal: 25n, claimableNow: 15n });
  const fullyClaimed = { ...purchase, claimed: 100n };
  assert.deepEqual(claimability(fullyClaimed, 100n), { vestedTotal: 100n, claimableNow: 0n });
  const controller = createIcoV2Controller(dependencies({ purchase: fullyClaimed, vestedTotal: 100n })); const res = response();
  await controller.buyer({ params: { address: buyer } }, res, (error) => { throw error; });
  assert.equal(res.body.data.vestedTotal, '100'); assert.equal(res.body.data.purchase.claimed, '100'); assert.equal(res.body.data.claimableNow, '0');
  assert.equal(Object.hasOwn(res.body.data, 'claimable'), false);
});
