const assert = require('node:assert/strict');
const test = require('node:test');
const { Interface } = require('ethers');
const artifact = require('../../../artifacts/contracts/treasury/TreasuryV2.sol/TreasuryV2.json');
const { TreasuryIndexer } = require('../modules/treasuryProjection/indexer.cjs');
const iface = new Interface(artifact.abi);
const address = (value) => `0x${value.toString(16).padStart(40, '0')}`;
const hash = (value) => `0x${value.toString(16).padStart(64, '0')}`;
const TREASURY = address(99); const ABCD = address(100); const FUNDER = address(2); const RECIPIENT = address(3); const ADMIN = address(4);
const manifest = { chainId: 31337, deploymentVersion: 'treasury-fixture', deploymentBlock: 10, treasuryAddress: TREASURY, abcdAddress: ABCD };
function log(name, values, blockNumber, index, transactionHash) { const encoded = iface.encodeEventLog(iface.getEvent(name), values); return { address: TREASURY, ...encoded, blockNumber, index, transactionHash: hash(transactionHash), blockHash: hash(10_000 + blockNumber) }; }
class Provider { constructor(logs) { this.logs = logs; } async getNetwork() { return { chainId: 31337n }; } async getCode() { return '0x6000'; } async getBlockNumber() { return 20; } async getBlock(number) { return { number, hash: hash(10_000 + Number(number)) }; } async getLogs(filter) { return this.logs.filter((item) => item.blockNumber >= Number(filter.fromBlock) && item.blockNumber <= Number(filter.toBlock)); } }
class Models { constructor() { this.events = []; this.assets = []; this.checkpoint = null; this.TreasuryEvent = { updateOne: async (filter, update) => { if (this.events.some((item) => item.transactionHash === filter.transactionHash && item.logIndex === filter.logIndex)) return { upsertedCount: 0 }; this.events.push(update.$setOnInsert); return { upsertedCount: 1 }; } }; this.TreasuryAsset = { updateOne: async (filter, update) => { const index = this.assets.findIndex((item) => item.asset === filter.asset); if (index < 0) this.assets.push({ ...update.$set }); else this.assets[index] = { ...this.assets[index], ...update.$set }; } }; this.TreasuryCheckpoint = { findOne: () => ({ lean: async () => this.checkpoint }), updateOne: async (_filter, update) => { this.checkpoint = { ...update.$set }; } }; } }
test('projects canonical TreasuryV2 events in block/log order and checkpoints the chain', async () => { const logs = [log('AssetConfigured', [ABCD, true, ADMIN], 10, 0, 1), log('FunderConfigured', [FUNDER, true, ADMIN], 11, 0, 2), log('TreasuryFunded', [hash(1), ABCD, FUNDER, 25n, 25n], 12, 0, 3), log('TreasuryTransferExecuted', [hash(2), ABCD, RECIPIENT, 25n, 0n], 13, 0, 4)]; const models = new Models(); const indexer = new TreasuryIndexer({ manifest, artifact, provider: new Provider(logs), models }); indexer.contract.supportedAsset = async () => true; indexer.contract.accountedBalance = async () => 0n; const result = await indexer.syncOnce(); assert.equal(result.processed, 4); assert.deepEqual(models.events.map((event) => event.eventName), ['AssetConfigured', 'FunderConfigured', 'TreasuryFunded', 'TreasuryTransferExecuted']); assert.equal(models.assets[0].accountedBalance, '0'); assert.equal(models.checkpoint.lastProcessedBlock, '20'); });
test('fails closed when deployment validation or checkpoint continuity is invalid', async () => { const models = new Models(); const indexer = new TreasuryIndexer({ manifest, artifact, provider: new Provider([]), models }); indexer.contract.supportedAsset = async () => true; indexer.provider.getCode = async () => '0x'; await assert.rejects(indexer.assertDeployment(), /bytecode or ABCD configuration is invalid/); indexer.provider.getCode = async () => '0x6000'; models.checkpoint = { lastProcessedBlock: '19', lastProcessedBlockHash: hash(1) }; await assert.rejects(indexer.syncOnce(), /checkpoint does not match active chain/); });
