import { Contract, Interface, formatUnits, isAddress, parseUnits } from 'ethers';
import AdapterArtifact from '../../artifacts/contracts/marketplace/LegionMarketplaceSettlementAdapterV2.sol/LegionMarketplaceSettlementAdapterV2.json';
import LegionArtifact from '../../artifacts/contracts/nft/LegionNFTV2.sol/LegionNFTV2.json';
import { getProvider, getSigner } from './wallet';

type Source = { chainId: string; settlementAddress: string; legionAddress: string; abcdAddress: string; deploymentVersion: string };
export type LegionSale = { saleId: string; tokenId: string; requestId?: string | null; seller: string; buyer: string; price: string; status: 'AWAITING_LEGION_REQUEST' | 'LEGION_REQUEST_PENDING' | 'LEGION_ADMIN_APPROVAL_PENDING' | 'READY_FOR_SETTLEMENT' | 'SETTLED' | 'CANCELLED' | 'STALE'; revalidation?: 'CURRENT' | 'STALE' | 'UNAVAILABLE'; revalidationReason?: string };
export type LegionMarketplaceSnapshot = { available: boolean; status: 'AVAILABLE' | 'UNAVAILABLE'; checkpoint?: string | null; reason?: string; source?: Source; sales: LegionSale[] };
type TransactionResult = { hash: string; receipt: { blockNumber: number | null }; indexed: boolean };
const api = '/api/legion-marketplace-v2';
const erc20 = ['function allowance(address,address) view returns (uint256)', 'function approve(address,uint256) returns (bool)'];
const adapterInterface = new Interface(AdapterArtifact.abi); const legionInterface = new Interface(LegionArtifact.abi);
const same = (left: string, right: string) => left.toLowerCase() === right.toLowerCase();
async function request<T>(path: string): Promise<T> { const response = await fetch(`${api}${path}`); const body = await response.json(); if (!response.ok) throw new Error(body.reason || body.message || `Legion marketplace API request failed (${response.status}).`); return body as T; }
function source(snapshot: LegionMarketplaceSnapshot): Source { if (!snapshot.available || !snapshot.source || snapshot.source.chainId !== '31337') throw new Error(snapshot.reason || 'Canonical Legion marketplace is unavailable.'); return snapshot.source; }
function expected(receipt: any, iface: Interface, name: string) { const found = receipt.logs.some((log: any) => { try { return iface.parseLog(log)?.name === name; } catch { return false; } }); if (!found) throw new Error(`Confirmed receipt did not contain ${name}.`); }
async function confirmed(tx: any, iface: Interface, event: string | null, label: string, stage?: (message: string, hash?: string) => void): Promise<TransactionResult> { stage?.('Confirming on-chain receipt', tx.hash); const receipt = await tx.wait(); if (!receipt || Number(receipt.status) !== 1) throw new Error(`${label} reverted or was not confirmed on-chain.`); if (event) expected(receipt, iface, event); return { hash: tx.hash, receipt: { blockNumber: receipt.blockNumber ?? null }, indexed: false }; }
async function revalidate(sale: LegionSale, details: Source): Promise<LegionSale> { try { const provider = await getProvider(); if ((await provider.getNetwork()).chainId !== 31337n) throw new Error('Wallet is not on Hardhat Local (31337).'); const legion = new Contract(details.legionAddress, LegionArtifact.abi, provider); const owner = await legion.ownerOf(BigInt(sale.tokenId)); if (!same(owner, sale.seller)) return { ...sale, revalidation: 'STALE', revalidationReason: 'Seller no longer owns this Legion NFT.' }; if (!sale.requestId) return { ...sale, revalidation: 'STALE', revalidationReason: 'The required controlled Legion transfer request is not indexed.' }; const transfer = await legion.getTransferRequest(BigInt(sale.requestId)); if (!transfer.active || !same(transfer.currentOwner, sale.seller) || !same(transfer.proposedOwner, sale.buyer)) return { ...sale, revalidation: 'STALE', revalidationReason: 'The linked Legion transfer request is no longer valid.' }; return { ...sale, revalidation: 'CURRENT' }; } catch (error) { return { ...sale, revalidation: 'UNAVAILABLE', revalidationReason: error instanceof Error ? error.message : 'Current on-chain Legion sale validation failed.' }; } }
export async function getLegionMarketplaceSnapshot(): Promise<LegionMarketplaceSnapshot> { const status: any = await request('/status'); if (!status.available) return { available: false, status: 'UNAVAILABLE', checkpoint: status.checkpoint, reason: status.reason, source: status.source, sales: [] }; const active: any = await request('/sales/active'); const snapshot: LegionMarketplaceSnapshot = { available: true, status: 'AVAILABLE', checkpoint: status.checkpoint, source: status.source, sales: Array.isArray(active.data) ? active.data : [] }; const details = source(snapshot); return { ...snapshot, sales: await Promise.all(snapshot.sales.map((sale) => revalidate(sale, details))) }; }
async function waitForIndexer(result: TransactionResult, eventName: string, stage?: (message: string, hash?: string) => void): Promise<TransactionResult> { stage?.('Confirmed on chain — waiting for indexer', result.hash); for (let attempt = 0; attempt < 20; attempt += 1) { try { const status: any = await request('/status'); if (status.available && result.receipt.blockNumber !== null && BigInt(status.checkpoint || 0) >= BigInt(result.receipt.blockNumber)) { const history: any = await request('/history?limit=100'); if (Array.isArray(history.data) && history.data.some((entry: any) => same(entry.transactionHash, result.hash) && entry.eventName === eventName)) { stage?.('Confirmed and indexed', result.hash); return { ...result, indexed: true }; } } } catch { /* The mined receipt remains canonical while indexer evidence is pending. */ } await new Promise((resolve) => setTimeout(resolve, 500)); } return result; }
async function contracts(snapshot: LegionMarketplaceSnapshot) { const details = source(snapshot); const signer = await getSigner(); const network = await signer.provider?.getNetwork(); if (network?.chainId !== 31337n) throw new Error('Switch MetaMask to Hardhat Local (31337) before using the canonical Legion marketplace.'); return { details, signer, adapter: new Contract(details.settlementAddress, AdapterArtifact.abi, signer), legion: new Contract(details.legionAddress, LegionArtifact.abi, signer) }; }
export async function createTargetedLegionSale(tokenIdText: string, buyer: string, priceText: string, stage?: (message: string, hash?: string) => void) { if (!/^\d+$/.test(tokenIdText) || BigInt(tokenIdText) === 0n || !isAddress(buyer)) throw new Error('Token ID and named buyer are invalid.'); const price = parseUnits(priceText, 18); if (price <= 0n) throw new Error('Price must be greater than zero ABCD.'); const snapshot = await getLegionMarketplaceSnapshot(); const { signer, adapter, legion } = await contracts(snapshot); const seller = await signer.getAddress(); const saleId = await adapter.createSale.staticCall(BigInt(tokenIdText), buyer, price); stage?.('Waiting for MetaMask targeted-sale confirmation'); await confirmed(await adapter.createSale(BigInt(tokenIdText), buyer, price), adapterInterface, 'SaleCreated', 'Legion sale creation', stage); const requestId = await legion.requestTransfer.staticCall(BigInt(tokenIdText), buyer); stage?.('Waiting for MetaMask Legion transfer-request confirmation'); await confirmed(await legion.requestTransfer(BigInt(tokenIdText), buyer), legionInterface, 'TransferRequested', 'Legion transfer request', stage); stage?.('Waiting for MetaMask sale/request-link confirmation'); return waitForIndexer(await confirmed(await adapter.linkTransferRequest(saleId, requestId), adapterInterface, 'SaleRequestLinked', 'Legion sale/request link', stage), 'SaleRequestLinked', stage); }
export async function cancelTargetedLegionSale(saleId: string, stage?: (message: string, hash?: string) => void) { if (!/^\d+$/.test(saleId) || BigInt(saleId) === 0n) throw new Error('Sale ID is invalid.'); const snapshot = await getLegionMarketplaceSnapshot(); const { adapter } = await contracts(snapshot); stage?.('Waiting for MetaMask cancellation confirmation'); return waitForIndexer(await confirmed(await adapter.cancelSale(BigInt(saleId)), adapterInterface, 'SaleCancelled', 'Legion sale cancellation', stage), 'SaleCancelled', stage); }
export async function approveTargetedLegionSale(requestId: string, stage?: (message: string, hash?: string) => void) { if (!/^\d+$/.test(requestId) || BigInt(requestId) === 0n) throw new Error('Transfer request ID is invalid.'); const snapshot = await getLegionMarketplaceSnapshot(); const { legion } = await contracts(snapshot); stage?.('Waiting for MetaMask Legion-admin approval'); return confirmed(await legion.approveTransfer(BigInt(requestId)), legionInterface, 'TransferApproved', 'Legion transfer approval', stage); }
export async function settleTargetedLegionSale(sale: LegionSale, stage?: (message: string, hash?: string) => void) { if (sale.revalidation !== 'CURRENT') throw new Error(sale.revalidationReason || 'The Legion sale is not currently settleable.'); const snapshot = await getLegionMarketplaceSnapshot(); const current = snapshot.sales.find((candidate) => candidate.saleId === sale.saleId); if (!current || current.revalidation !== 'CURRENT') throw new Error(current?.revalidationReason || 'The Legion sale is no longer settleable.'); const { details, signer, adapter } = await contracts(snapshot); const token = new Contract(details.abcdAddress, erc20, signer); const buyer = await signer.getAddress(); if (!same(buyer, sale.buyer)) throw new Error('Only the named buyer may settle this Legion sale.'); const price = BigInt(sale.price); if ((await token.allowance(buyer, details.settlementAddress)) < price) { stage?.('Waiting for MetaMask ABCD approval'); await confirmed(await token.approve(details.settlementAddress, price), new Interface(erc20), null, 'ABCD approval', stage); } stage?.('Waiting for MetaMask atomic settlement confirmation'); return waitForIndexer(await confirmed(await adapter.settleSale(BigInt(sale.saleId)), adapterInterface, 'SaleSettled', 'Legion settlement', stage), 'SaleSettled', stage); }
export const displayLegionABCD = (amount: string) => formatUnits(BigInt(amount), 18);
export function legionMarketplaceError(error: unknown) { const value = error as { code?: string | number; shortMessage?: string; reason?: string; message?: string }; const message = value.shortMessage || value.reason || value.message || 'Legion marketplace action failed.'; return value.code === 4001 || value.code === 'ACTION_REJECTED' || /rejected|denied/i.test(message) ? 'Transaction rejected in MetaMask. No on-chain state changed.' : message; }
