const { Contract, Interface } = require('ethers');
const EVENTS = ['AssetConfigured', 'FunderConfigured', 'RecipientConfigured', 'TreasuryFunded', 'TreasuryTransferExecuted', 'TreasuryPaused', 'TreasuryUnpaused'];
const lower = (value) => typeof value === 'string' ? value.toLowerCase() : value;
const serialise = (value) => typeof value === 'bigint' ? value.toString() : value;

class TreasuryIndexer {
  constructor({ manifest, artifact, provider, models }) { this.manifest = manifest; this.provider = provider; this.models = models; this.iface = new Interface(artifact.abi); this.contract = new Contract(manifest.treasuryAddress, artifact.abi, provider); this.topics = EVENTS.map((name) => this.iface.getEvent(name).topicHash); }
  identity() { return { chainId: String(this.manifest.chainId), deploymentVersion: this.manifest.deploymentVersion, treasuryAddress: this.manifest.treasuryAddress }; }
  async assertDeployment() { const [network, code, configured] = await Promise.all([this.provider.getNetwork(), this.provider.getCode(this.manifest.treasuryAddress), this.contract.supportedAsset(this.manifest.abcdAddress)]); if (Number(network.chainId) !== Number(this.manifest.chainId) || code === '0x' || !configured) throw new Error('TreasuryV2 bytecode or ABCD configuration is invalid.'); }
  async syncOnce() {
    await this.assertDeployment(); const identity = this.identity(); const prior = await this.models.TreasuryCheckpoint.findOne(identity).lean();
    if (prior?.lastProcessedBlock) { const block = await this.provider.getBlock(Number(prior.lastProcessedBlock)); if (!block || lower(block.hash) !== lower(prior.lastProcessedBlockHash)) throw new Error('TreasuryV2 checkpoint does not match active chain.'); }
    const latest = await this.provider.getBlockNumber(); const from = prior?.lastProcessedBlock ? Number(prior.lastProcessedBlock) + 1 : this.manifest.deploymentBlock;
    if (latest < from) return { checkpoint: prior?.lastProcessedBlock || null, processed: 0 };
    const logs = await this.provider.getLogs({ address: this.manifest.treasuryAddress, topics: [this.topics], fromBlock: from, toBlock: latest }); logs.sort((left, right) => Number(left.blockNumber) - Number(right.blockNumber) || Number(left.index ?? left.logIndex) - Number(right.index ?? right.logIndex));
    for (const log of logs) { const parsed = this.iface.parseLog({ topics: log.topics, data: log.data }); if (!parsed) continue; const args = Object.fromEntries(parsed.fragment.inputs.map((input, index) => [input.name || String(index), serialise(parsed.args[index])])); const event = { ...identity, transactionHash: lower(log.transactionHash), blockNumber: String(log.blockNumber), logIndex: Number(log.index ?? log.logIndex), blockHash: lower(log.blockHash), eventName: parsed.name, args, indexedAt: new Date() }; const inserted = await this.models.TreasuryEvent.updateOne({ ...identity, transactionHash: event.transactionHash, logIndex: event.logIndex }, { $setOnInsert: event }, { upsert: true }); if (!inserted.upsertedCount) continue; if (parsed.name === 'AssetConfigured') await this.models.TreasuryAsset.updateOne({ ...identity, asset: lower(args.asset) }, { $set: { ...identity, asset: lower(args.asset), supported: args.enabled, accountedBalance: String(await this.contract.accountedBalance(args.asset)), latestEvidence: event, indexedAt: new Date() } }, { upsert: true }); if (parsed.name === 'TreasuryFunded' || parsed.name === 'TreasuryTransferExecuted') await this.models.TreasuryAsset.updateOne({ ...identity, asset: lower(args.asset) }, { $set: { ...identity, asset: lower(args.asset), supported: true, accountedBalance: args.accountedBalance, latestEvidence: event, indexedAt: new Date() } }, { upsert: true }); }
    const checkpointBlock = await this.provider.getBlock(latest); await this.models.TreasuryCheckpoint.updateOne(identity, { $set: { ...identity, lastProcessedBlock: String(latest), lastProcessedBlockHash: lower(checkpointBlock.hash), indexedAt: new Date() } }, { upsert: true }); return { checkpoint: String(latest), processed: logs.length };
  }
}
module.exports={TreasuryIndexer,EVENTS};
