/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IP2PLoanMarketplace, IP2PLoanMarketplaceInterface } from "../../interfaces/IP2PLoanMarketplace.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "loanId",
        "type": "uint256"
      }
    ],
    "name": "markLoanNFTDefaulted",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "loanId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "releaseRepaidCollateral",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IP2PLoanMarketplace__factory {
    static readonly abi = _abi;
    static createInterface(): IP2PLoanMarketplaceInterface {
      return new Interface(_abi) as IP2PLoanMarketplaceInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IP2PLoanMarketplace {
      return new Contract(address, _abi, runner) as unknown as IP2PLoanMarketplace;
    }
  }
  