// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "../interfaces/IABCDTokenV2.sol";

interface IChainlinkPriceFeedV3 { function decimals() external view returns (uint8); function latestRoundData() external view returns (uint80, int256, uint256, uint256, uint80); }

/// @notice Owner-approved 1Q-model ICO. It sells existing ICO-allocation ABCD; it never mints.
/// @dev Economic and lifecycle rules intentionally match ICOManagerV2. Only custody is rebound
///      from the historical community allocation to ABCDTokenV2.icoWallet().
contract ICOManagerV3 is AccessControl, Pausable, ReentrancyGuard {
    using SafeERC20 for IERC20;
    bytes32 public constant ICO_ADMIN_ROLE = keccak256("ICO_ADMIN_ROLE"); bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE"); bytes32 public constant ORACLE_ADMIN_ROLE = keccak256("ORACLE_ADMIN_ROLE"); bytes32 public constant ELIGIBILITY_ADMIN_ROLE = keccak256("ELIGIBILITY_ADMIN_ROLE"); bytes32 public constant CUSTODY_ADMIN_ROLE = keccak256("CUSTODY_ADMIN_ROLE");
    uint256 public constant TOKEN_UNIT = 1e18; uint256 public constant ICO_INVENTORY = 50_000_000 * TOKEN_UNIT; uint256 public constant STAGE_ONE_INVENTORY = 25_000_000 * TOKEN_UNIT; uint256 public constant STAGE_TWO_INVENTORY = 25_000_000 * TOKEN_UNIT; uint256 public constant STAGE_ONE_PRICE_USD_WAD = 8e15; uint256 public constant STAGE_TWO_PRICE_USD_WAD = 1e16; uint256 public constant MIN_PURCHASE = 100 * TOKEN_UNIT; uint256 public constant MAX_PURCHASE_PER_WALLET = 500_000 * TOKEN_UNIT; uint256 public constant TGE_BPS = 2_500; uint256 public constant BPS_DENOMINATOR = 10_000; uint256 public constant STAGE_DURATION = 14 days; uint256 public constant VESTING_DURATION = 90 days;
    enum Lifecycle { NotStarted, Active, Finalized, Cancelled }
    struct Stage { uint256 startTime; uint256 endTime; uint256 inventory; uint256 sold; uint256 priceUsdWad; }
    struct Purchase { uint256 allocation; uint256 bnbPaid; uint256 claimed; uint256 stageOneAllocation; uint256 stageTwoAllocation; bool refunded; }
    IERC20 public immutable abcd; address public immutable icoWallet; address payable public proceedsRecipient; IChainlinkPriceFeedV3 public bnbUsdFeed; uint8 public feedDecimals; uint256 public immutable maxPriceAge; uint256 public immutable deploymentInventory; Lifecycle public lifecycle; uint256 public tgeTimestamp; uint256 public totalAllocated; uint256 public totalBnbCollected; uint256 public totalBnbRefunded; uint256 public totalBnbWithdrawn;
    Stage[2] private _stages; mapping(address => Purchase) private _purchases; mapping(address => bool) public eligibleWallet;
    error InvalidConfiguration(); error SaleNotActive(); error StageNotActive(); error InvalidStage(); error OracleUnavailable(); error OracleStale(); error OraclePrecision(); error PurchaseTooSmall(); error WalletPurchaseLimit(); error StageInventoryExceeded(); error InventoryDust(); error InsufficientPayment(); error NotFinalized(); error NotCancelled(); error NothingClaimable(); error AlreadyRefunded(); error InventoryNotFunded(); error WalletIneligible(); error TgeNotConfigured(); error TgeImmutable(); error CancellationAfterTge(); error InvalidRecipient(); error NothingToWithdraw(); error NativeTransferFailed();
    event StageConfigured(uint8 indexed stageId,uint256 startTime,uint256 endTime,uint256 inventory,uint256 priceUsdWad); event EligibilityUpdated(address indexed wallet,bool eligible); event OracleReplaced(address indexed previousFeed,address indexed nextFeed,uint8 decimals,uint256 maxPriceAge); event TgeConfigured(uint256 indexed tgeTimestamp,address indexed configuredBy); event ProceedsRecipientConfigured(address indexed previousRecipient,address indexed nextRecipient); event IcoPurchase(address indexed buyer,uint8 indexed stage,uint256 bnbPaid,uint256 allocation,uint256 oracleAnswer,uint80 oracleRoundId); event ExcessBnbRefunded(address indexed buyer,uint256 amount); event IcoFinalized(uint256 indexed tgeTimestamp,uint256 unsoldReturned); event IcoCancelled(address indexed admin); event IcoRefundClaimed(address indexed buyer,uint256 bnbAmount,uint256 allocationReversed); event IcoTokensClaimed(address indexed buyer,uint256 amount,uint256 totalClaimed); event VestingCompleted(address indexed buyer,uint256 allocation); event ProceedsWithdrawn(address indexed recipient,uint256 amount,uint256 totalWithdrawn);
    constructor(address tokenAddress,address icoWallet_,address payable proceedsRecipient_,address bnbUsdFeed_,uint256 maxPriceAge_,uint256 stageOneStart,uint256 stageOneEnd,uint256 stageTwoStart,uint256 stageTwoEnd,address admin) {
        if (tokenAddress==address(0)||icoWallet_==address(0)||proceedsRecipient_==address(0)||bnbUsdFeed_==address(0)||admin==address(0)||maxPriceAge_==0) revert InvalidConfiguration();
        if (stageOneStart>=stageOneEnd||stageTwoStart>=stageTwoEnd||stageTwoStart<stageOneEnd||stageOneEnd-stageOneStart!=STAGE_DURATION||stageTwoEnd-stageTwoStart!=STAGE_DURATION) revert InvalidConfiguration();
        if (IABCDTokenV2(tokenAddress).icoWallet()!=icoWallet_) revert InvalidConfiguration();
        abcd=IERC20(tokenAddress); icoWallet=icoWallet_; proceedsRecipient=proceedsRecipient_; maxPriceAge=maxPriceAge_; deploymentInventory=ICO_INVENTORY; _setFeed(bnbUsdFeed_);
        _stages[0]=Stage(stageOneStart,stageOneEnd,STAGE_ONE_INVENTORY,0,STAGE_ONE_PRICE_USD_WAD); _stages[1]=Stage(stageTwoStart,stageTwoEnd,STAGE_TWO_INVENTORY,0,STAGE_TWO_PRICE_USD_WAD);
        _grantRole(DEFAULT_ADMIN_ROLE,admin); _grantRole(ICO_ADMIN_ROLE,admin); _grantRole(PAUSER_ROLE,admin); _grantRole(ORACLE_ADMIN_ROLE,admin); _grantRole(ELIGIBILITY_ADMIN_ROLE,admin); _grantRole(CUSTODY_ADMIN_ROLE,admin);
        emit StageConfigured(0,stageOneStart,stageOneEnd,STAGE_ONE_INVENTORY,STAGE_ONE_PRICE_USD_WAD); emit StageConfigured(1,stageTwoStart,stageTwoEnd,STAGE_TWO_INVENTORY,STAGE_TWO_PRICE_USD_WAD);
    }
    receive() external payable { revert InvalidConfiguration(); }
    function setEligibility(address wallet,bool allowed) external onlyRole(ELIGIBILITY_ADMIN_ROLE) whenNotPaused { if(wallet==address(0)) revert InvalidConfiguration(); eligibleWallet[wallet]=allowed; emit EligibilityUpdated(wallet,allowed); }
    function setOracle(address nextFeed) external onlyRole(ORACLE_ADMIN_ROLE) whenPaused { address previous=address(bnbUsdFeed); _setFeed(nextFeed); emit OracleReplaced(previous,nextFeed,feedDecimals,maxPriceAge); }
    function setProceedsRecipient(address payable nextRecipient) external onlyRole(CUSTODY_ADMIN_ROLE) whenPaused { if(nextRecipient==address(0)) revert InvalidRecipient(); address previous=proceedsRecipient; proceedsRecipient=nextRecipient; emit ProceedsRecipientConfigured(previous,nextRecipient); }
    function configureTge(uint256 timestamp) external onlyRole(ICO_ADMIN_ROLE) whenNotPaused { if(lifecycle==Lifecycle.Finalized||lifecycle==Lifecycle.Cancelled||tgeTimestamp!=0||timestamp<_stages[1].endTime) revert TgeImmutable(); tgeTimestamp=timestamp; emit TgeConfigured(timestamp,msg.sender); }
    function buy(uint8 stageId,uint256 requestedAllocation) external payable nonReentrant whenNotPaused {
        if(!eligibleWallet[msg.sender]) revert WalletIneligible(); if(lifecycle==Lifecycle.Finalized||lifecycle==Lifecycle.Cancelled) revert SaleNotActive(); if(stageId>1) revert InvalidStage(); Stage storage s=_stages[stageId]; if(block.timestamp<s.startTime||block.timestamp>=s.endTime) revert StageNotActive(); if(requestedAllocation<MIN_PURCHASE) revert PurchaseTooSmall(); if(s.inventory-s.sold<MIN_PURCHASE) revert InventoryDust(); if(requestedAllocation>s.inventory-s.sold||requestedAllocation>ICO_INVENTORY-totalAllocated) revert StageInventoryExceeded(); if(abcd.balanceOf(address(this))<ICO_INVENTORY-totalAllocated) revert InventoryNotFunded(); Purchase storage p=_purchases[msg.sender]; if(p.allocation+requestedAllocation>MAX_PURCHASE_PER_WALLET) revert WalletPurchaseLimit();
        (uint80 roundId,uint256 bnbUsdWad)=_bnbUsdWad(); uint256 requiredBnb=_ceilDiv(requestedAllocation*s.priceUsdWad,bnbUsdWad); if(msg.value<requiredBnb||requiredBnb==0) revert InsufficientPayment(); uint256 excess=msg.value-requiredBnb; lifecycle=Lifecycle.Active; s.sold+=requestedAllocation; totalAllocated+=requestedAllocation; p.allocation+=requestedAllocation; p.bnbPaid+=requiredBnb; if(stageId==0) p.stageOneAllocation+=requestedAllocation; else p.stageTwoAllocation+=requestedAllocation; totalBnbCollected+=requiredBnb; if(excess>0){(bool refunded,)=payable(msg.sender).call{value:excess}("");if(!refunded) revert NativeTransferFailed();emit ExcessBnbRefunded(msg.sender,excess);} emit IcoPurchase(msg.sender,stageId,requiredBnb,requestedAllocation,bnbUsdWad,roundId);
    }
    function finalize() external onlyRole(ICO_ADMIN_ROLE) nonReentrant whenNotPaused { if(lifecycle==Lifecycle.Finalized||lifecycle==Lifecycle.Cancelled) revert SaleNotActive(); if(block.timestamp<_stages[1].endTime) revert StageNotActive(); if(tgeTimestamp==0||tgeTimestamp>block.timestamp) revert TgeNotConfigured(); if(abcd.balanceOf(address(this))<ICO_INVENTORY) revert InventoryNotFunded(); lifecycle=Lifecycle.Finalized; uint256 unsold=ICO_INVENTORY-totalAllocated; if(unsold>0) abcd.safeTransfer(icoWallet,unsold); emit IcoFinalized(tgeTimestamp,unsold); }
    function cancel() external onlyRole(ICO_ADMIN_ROLE) nonReentrant whenNotPaused { if(lifecycle==Lifecycle.Finalized||lifecycle==Lifecycle.Cancelled||(tgeTimestamp!=0&&block.timestamp>=tgeTimestamp)) revert CancellationAfterTge(); lifecycle=Lifecycle.Cancelled; uint256 unsold=ICO_INVENTORY-totalAllocated; if(unsold>0) abcd.safeTransfer(icoWallet,unsold); emit IcoCancelled(msg.sender); }
    function claimRefund() external nonReentrant { if(lifecycle!=Lifecycle.Cancelled) revert NotCancelled(); Purchase storage p=_purchases[msg.sender]; if(p.refunded) revert AlreadyRefunded(); uint256 amount=p.bnbPaid; uint256 allocation=p.allocation; if(amount==0||allocation==0) revert NothingClaimable(); p.refunded=true;p.bnbPaid=0;p.allocation=0;totalBnbRefunded+=amount;totalAllocated-=allocation;_stages[0].sold-=p.stageOneAllocation;_stages[1].sold-=p.stageTwoAllocation;p.stageOneAllocation=0;p.stageTwoAllocation=0;abcd.safeTransfer(icoWallet,allocation);(bool sent,)=payable(msg.sender).call{value:amount}("");if(!sent) revert NativeTransferFailed();emit IcoRefundClaimed(msg.sender,amount,allocation); }
    function withdrawProceeds() external onlyRole(CUSTODY_ADMIN_ROLE) nonReentrant whenNotPaused { if(lifecycle!=Lifecycle.Finalized) revert NotFinalized(); uint256 amount=address(this).balance;if(amount==0) revert NothingToWithdraw();totalBnbWithdrawn+=amount;(bool sent,)=proceedsRecipient.call{value:amount}("");if(!sent) revert NativeTransferFailed();emit ProceedsWithdrawn(proceedsRecipient,amount,totalBnbWithdrawn); }
    function claim() external nonReentrant { if(lifecycle!=Lifecycle.Finalized) revert NotFinalized(); Purchase storage p=_purchases[msg.sender];uint256 available=claimable(msg.sender);if(available<=p.claimed) revert NothingClaimable();uint256 amount=available-p.claimed;p.claimed+=amount;abcd.safeTransfer(msg.sender,amount);emit IcoTokensClaimed(msg.sender,amount,p.claimed);if(p.claimed==p.allocation) emit VestingCompleted(msg.sender,p.allocation); }
    function claimable(address buyer) public view returns(uint256) { if(lifecycle!=Lifecycle.Finalized||tgeTimestamp==0||block.timestamp<tgeTimestamp) return 0;uint256 allocation=_purchases[buyer].allocation;uint256 tge=allocation*TGE_BPS/BPS_DENOMINATOR;uint256 remainder=allocation-tge;uint256 elapsed=block.timestamp-tgeTimestamp;return elapsed>=VESTING_DURATION?allocation:tge+(remainder*elapsed/VESTING_DURATION); }
    function stage(uint8 stageId) external view returns(Stage memory) {if(stageId>1) revert InvalidStage();return _stages[stageId];} function purchaseOf(address buyer) external view returns(Purchase memory){return _purchases[buyer];} function currentStage() external view returns(uint8){if(block.timestamp>=_stages[0].startTime&&block.timestamp<_stages[0].endTime)return 0;if(block.timestamp>=_stages[1].startTime&&block.timestamp<_stages[1].endTime)return 1;return type(uint8).max;} function pause() external onlyRole(PAUSER_ROLE){_pause();} function unpause() external onlyRole(PAUSER_ROLE){_unpause();}
    function _setFeed(address nextFeed) private {if(nextFeed==address(0)) revert InvalidConfiguration();uint8 decimals_=IChainlinkPriceFeedV3(nextFeed).decimals();if(decimals_==0||decimals_>18) revert OraclePrecision();bnbUsdFeed=IChainlinkPriceFeedV3(nextFeed);feedDecimals=decimals_;_bnbUsdWad();} function _bnbUsdWad() private view returns(uint80 roundId,uint256 priceWad){int256 answer;uint256 updatedAt;uint80 answeredInRound;(roundId,answer,,updatedAt,answeredInRound)=bnbUsdFeed.latestRoundData();if(roundId==0||answer<=0||updatedAt==0||answeredInRound<roundId||updatedAt>block.timestamp) revert OracleUnavailable();if(block.timestamp-updatedAt>maxPriceAge) revert OracleStale();priceWad=uint256(answer)*TOKEN_UNIT/(10**feedDecimals);if(priceWad==0) revert OracleUnavailable();} function _ceilDiv(uint256 a,uint256 b) private pure returns(uint256){return a/b+(a%b==0?0:1);}
}
