const express = require('express');
const { loadLendingV2Manifest } = require('../../config/lendingV2Manifest.cjs');
const { loadLendingV2Artifacts } = require('../../config/lendingV2Artifacts.cjs');
const models = require('./models.cjs');
const { createLendingV2ReadController } = require('./lendingV2Read.controller.cjs');
const controller = createLendingV2ReadController({ manifest: loadLendingV2Manifest(), artifacts: loadLendingV2Artifacts(), models });
const router = express.Router();
router.get('/status', controller.status);
router.get('/requests/open', controller.openRequests);
router.get('/requests/:requestId', controller.request);
router.get('/wallet/:address', controller.wallet);
router.get('/loans/:loanId', controller.loan);
router.get('/loans/:loanId/history', controller.history);
router.get('/loans/:loanId/preview', controller.preview);
module.exports = router;
