const path = require('node:path');
require('dotenv').config({ path: path.resolve(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const { JsonRpcProvider } = require('ethers');
const connectDb = require('../config/db');
const logger = require('../logger');
const { selectedRuntimeFamily, verifyBackendRuntimeFamilyLive } = require('../config/runtimeFamily.cjs');
const { loadLegionNFTV2Manifest } = require('../config/legionNFTV2Manifest.cjs');
const { loadLegionNFTV2Artifact } = require('../config/legionNFTV2Artifacts.cjs');
const models = require('../modules/legionNFTV2Projection/models.cjs');
const { LegionNFTV2Indexer } = require('../modules/legionNFTV2Projection/indexer.cjs');
(async () => { selectedRuntimeFamily(); await verifyBackendRuntimeFamilyLive(); const manifest = loadLegionNFTV2Manifest(); await connectDb(); const indexer = new LegionNFTV2Indexer({ manifest, artifact: loadLegionNFTV2Artifact(), provider: new JsonRpcProvider(manifest.rpcUrl), models, logger, confirmations: 0 }); const stop = async () => { await indexer.stop(); await mongoose.disconnect(); process.exit(0); }; process.once('SIGINT', stop); process.once('SIGTERM', stop); await indexer.start(); })().catch((error) => { logger.error({ component: 'legion-nft-v2-indexer', message: error.message }); process.exit(1); });
