import React, { useCallback, useEffect, useState } from 'react';
import { RefreshCcw, ShoppingCart, Tag } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import { cancelABCDListing, createABCDListing, displayABCD, getABCDMarketplaceSnapshot, marketplaceError, purchaseABCDListing, type MarketplaceListing, type MarketplaceSnapshot } from '../Services/abcdNftMarketplaceV2';

const empty: MarketplaceSnapshot = { available: false, status: 'UNAVAILABLE', listings: [] };
const same = (a?: string | null, b?: string | null) => Boolean(a && b && a.toLowerCase() === b.toLowerCase());
export const ABCDNFTMarketplaceV2Dashboard: React.FC = () => {
  const wallet = useWallet(); const [snapshot, setSnapshot] = useState<MarketplaceSnapshot>(empty); const [collection, setCollection] = useState(''); const [tokenId, setTokenId] = useState(''); const [price, setPrice] = useState(''); const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const refresh = useCallback(async () => { try { setError(''); setSnapshot(await getABCDMarketplaceSnapshot()); } catch (reason) { setSnapshot(empty); setError(marketplaceError(reason)); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (key: string, action: (stage: (message: string, hash?: string) => void) => Promise<{ hash: string }>) => { if (busy) return; setBusy(key); setError(''); setNotice('Waiting for MetaMask confirmation'); try { const result = await action((message, hash) => setNotice(hash ? `${message}: ${hash}` : message)); setNotice(`Confirmed: ${result.hash}. Refreshing canonical indexed state…`); await refresh(); } catch (reason) { setError(marketplaceError(reason)); } finally { setBusy(null); } };
  return <section aria-label="Canonical ABCD NFT marketplace" className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-emerald-500/30 bg-slate-900 p-6 shadow-xl">
    <header className="flex flex-wrap justify-between gap-3 border-b border-slate-800 pb-4"><div><p className="text-xs font-black uppercase tracking-wide text-emerald-300">Canonical Phase 10A local market</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-black text-white"><ShoppingCart className="h-5 w-5" /> ABCD NFT Marketplace</h2><p className="mt-1 text-sm text-slate-400">Supported collections only. Listings are non-custodial: purchase transfers exactly the listed ABCD amount to the seller and the NFT to the buyer atomically.</p></div><button onClick={() => void refresh()} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-100"><RefreshCcw className="mr-2 inline h-4 w-4" />Refresh</button></header>
    {snapshot.source && <p className="break-all text-xs text-slate-500">Marketplace {snapshot.source.marketplaceAddress} · ABCD {snapshot.source.abcdAddress} · chain {snapshot.source.chainId} · checkpoint {snapshot.checkpoint || 'pending'}</p>}
    {error && <p className="rounded-xl border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-100">{error}</p>}{notice && <p className="rounded-xl border border-emerald-500/40 bg-emerald-500/10 p-3 text-sm text-emerald-100">{notice}</p>}
    {!snapshot.available && <p className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100">{snapshot.reason || 'The canonical marketplace deployment/indexer is unavailable.'}</p>}
    {snapshot.available && <form className="grid gap-2 rounded-2xl border border-slate-700 bg-slate-950/60 p-4 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); void run('create', (stage) => createABCDListing(collection, tokenId, price, stage)); }}><input aria-label="NFT collection" value={collection} onChange={(event) => setCollection(event.target.value)} placeholder="Supported collection address" className="field" /><input aria-label="NFT token ID" value={tokenId} onChange={(event) => setTokenId(event.target.value)} placeholder="Token ID" className="field" /><input aria-label="ABCD fixed price" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="Fixed ABCD price" className="field" /><button disabled={Boolean(busy) || !wallet.address} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50"><Tag className="mr-1 inline h-4 w-4" />Create listing</button></form>}
    <div className="space-y-3">{snapshot.listings.length === 0 ? <p className="rounded-xl border border-slate-700 p-4 text-sm text-slate-400">No active canonical listings are indexed.</p> : snapshot.listings.map((listing) => <Listing key={listing.listingId} listing={listing} wallet={wallet.address} busy={Boolean(busy)} purchase={() => void run(`buy-${listing.listingId}`, (stage) => purchaseABCDListing(listing, stage))} cancel={() => void run(`cancel-${listing.listingId}`, (stage) => cancelABCDListing(listing.listingId, stage))} />)}</div>
  </section>;
};
const Listing = ({ listing, wallet, busy, purchase, cancel }: { listing: MarketplaceListing; wallet: string | null; busy: boolean; purchase: () => void; cancel: () => void }) => <article className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-700 bg-slate-950/70 p-4"><div className="text-xs text-slate-400"><p className="font-black text-white">Listing #{listing.listingId} · {displayABCD(listing.price)} ABCD</p><p className="mt-1 break-all">Collection {listing.collection} · token #{listing.tokenId}</p><p className="break-all">Seller {listing.seller}</p></div>{same(wallet, listing.seller) ? <button onClick={cancel} disabled={busy} className="rounded-lg border border-rose-400/60 px-3 py-2 text-xs font-bold text-rose-100 disabled:opacity-50">Cancel</button> : <button onClick={purchase} disabled={busy || !wallet} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Approve ABCD if needed & buy</button>}</article>;
