import React, { useCallback, useEffect, useState } from 'react';
import { formatIcoV2Abcd, formatIcoV2UsdWad, normalizeIcoV2AdminStage, type IcoV2AdminStage } from '../Services/icoV2AdminStage';

type IcoStatus = { status: string; reason?: string; manifest?: { chainId: number; deploymentVersion: string; address: string }; checkpoint?: { lastProcessedBlock: string; lastProcessedBlockHash: string }; data?: { lifecycle: string; stages: unknown[]; totalAllocated: string; totalBnbCollected: string; totalBnbRefunded: string; totalBnbWithdrawn: string; tgeTimestamp: string; paused: boolean; oracle: { feed: string; feedDecimals: string; maxPriceAge: string }; proceedsRecipient: string; aggregates: Record<string, string | number> } };
const value = (input: unknown) => String(input ?? '0');

const stageLine = (stage: IcoV2AdminStage, index: number) => <>Stage {index + 1}: inventory {formatIcoV2Abcd(stage.inventory)} · sold {formatIcoV2Abcd(stage.sold)} · price {formatIcoV2UsdWad(stage.priceUsdWad)} · {stage.startTime}–{stage.endTime}</>;

/** Phase 6 canonical administrator read surface. It intentionally has no generic contract-write control. */
export const CanonicalIcoV2Admin: React.FC = () => {
  const [status, setStatus] = useState<IcoStatus | null>(null); const [reason, setReason] = useState('Loading canonical ICO V2 indexed state…');
  const load = useCallback(async () => { try { const response = await fetch('/api/ico-v2/status'); const body = await response.json().catch(() => ({})); if (!response.ok || body.status !== 'AVAILABLE') throw new Error(body.reason || 'Canonical ICO V2 API is unavailable.'); setStatus(body); setReason(''); } catch (error) { setStatus(null); setReason(error instanceof Error ? error.message : 'Canonical ICO V2 API is unavailable.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (!status?.data || !status.manifest || !status.checkpoint) return <section aria-label="Canonical ICO V2 Admin" className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100">ICO V2 canonical read state unavailable: {reason}</section>;
  const data = status.data; const aggregates = data.aggregates || {};
  const stages = data.stages.map(normalizeIcoV2AdminStage);
  if (stages.length !== 2 || stages.some((stage) => stage === null)) return <section aria-label="Canonical ICO V2 Admin" className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100">ICO V2 canonical read state unavailable: malformed stage tuple from the canonical API.</section>;
  const canonicalStages = stages.filter((stage): stage is IcoV2AdminStage => stage !== null);
  return <section aria-label="Canonical ICO V2 Admin" className="space-y-3 rounded-xl border border-cyan-500/30 bg-slate-950/70 p-4 text-xs"><header className="flex items-center justify-between gap-3"><div><p className="font-black text-cyan-200">Canonical ICO V2</p><p className="mt-1 text-slate-400">Read-only, deployment-scoped ICOManagerV2 reconciliation. No unverified administrative action is exposed.</p></div><button onClick={() => void load()} className="rounded-lg border border-slate-700 px-3 py-2 font-bold text-slate-100">Refresh</button></header><p className="break-all text-slate-400">Chain {status.manifest.chainId} · deployment {status.manifest.deploymentVersion} · ICO {status.manifest.address} · checkpoint {status.checkpoint.lastProcessedBlock} / {status.checkpoint.lastProcessedBlockHash}</p><div className="grid gap-2 md:grid-cols-3">{canonicalStages.map((stage, index) => <p key={index} className="rounded-lg border border-slate-700 p-3 text-slate-300">{stageLine(stage, index)}</p>)}</div><div className="grid gap-2 md:grid-cols-3 text-slate-300"><p>Allocations: {data.totalAllocated}</p><p>Purchases: {value(aggregates.purchases)}</p><p>Refunds: {value(aggregates.refunds)}</p><p>Cancellations: {value(aggregates.cancellations)}</p><p>Claims: {value(aggregates.claims)}</p><p>Vesting completions: {value(aggregates.vestingCompletions)}</p><p>BNB collected/refunded/withdrawn: {data.totalBnbCollected}/{data.totalBnbRefunded}/{data.totalBnbWithdrawn}</p><p>Pause: {data.paused ? 'PAUSED' : 'ACTIVE'}</p><p>TGE: {data.tgeTimestamp}</p><p className="break-all">Oracle: {data.oracle.feed} · decimals {data.oracle.feedDecimals} · max age {data.oracle.maxPriceAge}</p><p className="break-all">Proceeds recipient: {data.proceedsRecipient}</p><p>API health: {status.status} · reconciliation: checkpoint verified</p></div></section>;
};
