import React, { useCallback, useEffect, useState } from 'react';
import { Building2, RefreshCcw, ShieldAlert } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import { cancelFranchiseApplication, cancelFranchiseTransfer, getFranchiseWalletSnapshot, requestFranchiseTransfer, submitFranchiseApplication, type FranchiseCertificate, type FranchiseEvent } from '../Services/franchiseRegistryV2';

type Snapshot = Awaited<ReturnType<typeof getFranchiseWalletSnapshot>>;
const empty: Snapshot = { available: false, status: 'UNAVAILABLE', franchises: [], applications: [], history: {} };

/** Canonical Phase 9 Legion-bound, non-financial Franchise V2 user surface. */
export const FranchiseRegistryDashboard: React.FC = () => {
  const wallet = useWallet(); const [snapshot, setSnapshot] = useState<Snapshot>(empty); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [legionTokenId, setLegionTokenId] = useState(''); const [metadataURI, setMetadataURI] = useState(''); const [proposedOwners, setProposedOwners] = useState<Record<string, string>>({});
  const refresh = useCallback(async () => { setLoading(true); setMessage(null); try { setSnapshot(wallet.address ? await getFranchiseWalletSnapshot(wallet.address) : empty); } catch (reason) { setSnapshot(empty); setMessage(reason instanceof Error ? reason.message : 'Unable to read canonical Legion-bound Franchise V2 state.'); } finally { setLoading(false); } }, [wallet.address]);
  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (label: string, action: (submitted: (hash: string) => void) => Promise<unknown>) => { try { setMessage(`Confirm ${label} in your wallet.`); await action((hash) => setMessage(`${label} submitted: ${hash}. Waiting for indexed reconciliation.`)); await refresh(); setMessage(`${label} confirmed on-chain. The canonical UI will refresh after its indexed checkpoint advances.`); } catch (error) { setMessage(error instanceof Error ? error.message : `${label} failed.`); } };
  const canWrite = Boolean(wallet.address && wallet.isCorrectNetwork && snapshot.available);
  return <section aria-label="Canonical Legion-bound Franchise V2 dashboard" className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-teal-500/30 bg-slate-900 p-6 shadow-xl">
    <header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-800 pb-4"><div><p className="text-xs font-black uppercase tracking-wide text-teal-300">Canonical Phase 9 owner protocol decision</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-black text-white"><Building2 className="h-5 w-5" /> Franchise</h2><p className="mt-1 max-w-3xl text-sm text-slate-400">A non-financial application and assignment bound to a canonical Legion territory. It conveys no legal territory title, price, purchase, commission, Treasury, lending, referral, marketplace, or reward right.</p></div><button onClick={() => void refresh()} disabled={loading} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-100 disabled:opacity-50"><RefreshCcw className={`mr-2 inline h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></header>
    {snapshot.source && <p className="break-all text-xs text-slate-500">Legion {snapshot.source.legionAddress} · Registry {snapshot.source.registryAddress} · NFT {snapshot.source.nftAddress} · chain {snapshot.source.chainId} · checkpoint {snapshot.checkpoint || 'pending'}</p>}
    {message && <Notice text={message} />}{!wallet.address && <Notice text="Connect a wallet to use canonical Franchise V2." />}{wallet.address && !wallet.isCorrectNetwork && <Notice text="Switch MetaMask to Hardhat Local (31337) before using Franchise V2." />}{wallet.address && !snapshot.available && <Notice text={snapshot.reason || 'The canonical Legion-bound Franchise V2 deployment is not available or not indexed.'} />}
    {snapshot.available && <section className="rounded-2xl border border-slate-700 bg-slate-950/60 p-5"><h3 className="font-black text-white">Available territory application</h3><p className="mt-1 text-xs text-slate-400">Submit an application for a real canonical Legion country, state, or district token. The Registry validates the exact token on-chain; this creates no payment or financial obligation.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label="Legion territory token ID" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" placeholder="Legion token ID" value={legionTokenId} onChange={(event) => setLegionTokenId(event.target.value)} /><input aria-label="Franchise metadata IPFS URI" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" placeholder="ipfs://…" value={metadataURI} onChange={(event) => setMetadataURI(event.target.value)} /></div><button disabled={!canWrite || !/^\d+$/.test(legionTokenId) || !metadataURI.startsWith('ipfs://')} onClick={() => void run('Franchise application', (submitted) => submitFranchiseApplication(snapshot.source, legionTokenId, metadataURI, submitted))} className="mt-3 rounded-lg bg-teal-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Submit application</button></section>}
    {snapshot.available && <section className="rounded-2xl border border-slate-700 bg-slate-950/60 p-5"><h3 className="font-black text-white">Your applications</h3>{snapshot.applications.length === 0 ? <p className="mt-2 text-sm text-slate-400">No canonical application is indexed for this wallet.</p> : <div className="mt-3 space-y-2">{snapshot.applications.map((application) => <div key={application.applicationId} className="rounded-lg border border-slate-800 p-3 text-xs text-slate-300">Application #{application.applicationId} · Legion #{application.legionTokenId} · {application.status}<p className="mt-1 break-all text-slate-500">{application.metadataURI}</p>{['PENDING', 'APPROVED'].includes(application.status) && <button disabled={!canWrite} onClick={() => void run('Application cancellation', (submitted) => cancelFranchiseApplication(snapshot.source, application.applicationId, submitted))} className="mt-2 rounded border border-slate-600 px-2 py-1 text-xs disabled:opacity-50">Cancel application</button>}</div>)}</div>}</section>}
    {snapshot.available && snapshot.franchises.length === 0 && <p className="rounded-xl border border-slate-700 bg-slate-950/60 p-5 text-sm text-slate-300">No canonical Franchise V2 assignments are indexed for this wallet.</p>}
    {snapshot.franchises.map((franchise) => <FranchiseCard key={franchise.tokenId} franchise={franchise} events={snapshot.history[franchise.tokenId] || []} proposedOwner={proposedOwners[franchise.tokenId] || ''} canWrite={canWrite} onProposedOwner={(value) => setProposedOwners((current) => ({ ...current, [franchise.tokenId]: value }))} onRequest={() => void run('Controlled transfer request', (submitted) => requestFranchiseTransfer(snapshot.source, franchise.tokenId, proposedOwners[franchise.tokenId] || '', submitted))} onCancel={(requestId) => void run('Transfer cancellation', (submitted) => cancelFranchiseTransfer(snapshot.source, requestId, submitted))} />)}
    <aside className="rounded-xl border border-slate-700 bg-slate-950/60 p-4 text-xs text-slate-400">Transfers use only request → on-chain approval by an authorized Franchise role → current owner execution. This user surface never lists, sells, prices, pays for, collateralizes, or rewards a Franchise certificate.</aside>
  </section>;
};
const FranchiseCard = ({ franchise, events, proposedOwner, canWrite, onProposedOwner, onRequest, onCancel }: { franchise: FranchiseCertificate; events: FranchiseEvent[]; proposedOwner: string; canWrite: boolean; onProposedOwner: (value: string) => void; onRequest: () => void; onCancel: (requestId: string) => void }) => <article className="space-y-4 rounded-2xl border border-slate-700 bg-slate-950/70 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Franchise #{franchise.tokenId} · Legion #{franchise.legionTokenId}</p><h3 className="mt-1 text-lg font-black text-white">Legion-bound assignment</h3></div><span className="rounded-full border border-teal-400/40 px-3 py-1 text-xs font-bold text-teal-200">{franchise.status}</span></div><dl className="grid gap-3 text-xs sm:grid-cols-2"><Field label="Canonical Legion contract" value={franchise.legionContract} /><Field label="Current ERC-721 owner" value={franchise.owner} /><Field label="Registry operator" value={franchise.operator} /><Field label="Operator version" value={franchise.operatorVersion} /><Field label="Metadata URI" value={franchise.metadataURI} /></dl>{franchise.status === 'ACTIVE' && <div className="border-t border-slate-800 pt-3"><p className="text-xs font-bold text-slate-300">Controlled transfer</p>{franchise.activeTransferRequestId !== '0' ? <button disabled={!canWrite} onClick={() => onCancel(franchise.activeTransferRequestId)} className="mt-2 rounded border border-slate-600 px-2 py-1 text-xs text-slate-200 disabled:opacity-50">Cancel request #{franchise.activeTransferRequestId}</button> : <div className="mt-2 flex gap-2"><input aria-label={`Proposed owner for Franchise ${franchise.tokenId}`} className="min-w-0 flex-1 rounded border border-slate-700 bg-slate-900 px-2 py-1 text-xs text-white" value={proposedOwner} placeholder="Proposed wallet" onChange={(event) => onProposedOwner(event.target.value)} /><button disabled={!canWrite || !/^0x[a-fA-F0-9]{40}$/.test(proposedOwner)} onClick={onRequest} className="rounded bg-teal-600 px-2 py-1 text-xs font-bold text-white disabled:opacity-50">Request</button></div>}</div>}<div className="border-t border-slate-800 pt-3"><p className="text-xs font-black uppercase tracking-wide text-slate-400">Canonical provenance</p>{events.length === 0 ? <p className="mt-2 text-xs text-slate-500">No confirmed event is indexed yet.</p> : <ol className="mt-2 space-y-2">{events.map((event) => <li key={`${event.transactionHash}:${event.logIndex}`} className="break-all text-xs text-slate-400">{event.eventName} · block {event.blockNumber} · {event.transactionHash}</li>)}</ol>}</div></article>;
const Field = ({ label, value }: { label: string; value: string }) => <div><dt className="uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all text-slate-200">{value}</dd></div>;
const Notice = ({ text }: { text: string }) => <div className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-100"><ShieldAlert className="mr-2 inline h-4 w-4" />{text}</div>;
