import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, Coins, RefreshCw } from 'lucide-react';
import { formatEther } from 'ethers';
import { useWallet } from '../Context/WalletContext';
import { getIcoV3Snapshot, type IcoV3Snapshot } from '../Services/icoV3Read';

const amount = (value: string) => `${formatEther(value)} ABCD`;
const bnb = (value: string) => `${formatEther(value)} BNB`;

/** Canonical 1Q ICO read surface. The historical ICO V2 ABI is never used. */
export const ICOv2Dashboard: React.FC = () => {
  const { address } = useWallet();
  const [snapshot, setSnapshot] = useState<IcoV3Snapshot | null>(null);
  const [message, setMessage] = useState('Reading canonical ICOManagerV3 indexed state…');
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setSnapshot(await getIcoV3Snapshot(address || undefined)); setMessage(''); } catch (error) { setSnapshot(null); setMessage(error instanceof Error ? error.message : 'ICOManagerV3 is unavailable.'); } finally { setLoading(false); } }, [address]);
  useEffect(() => { void load(); }, [load]);
  return <section className="mx-auto max-w-5xl space-y-6 pb-12"><header className="rounded-3xl border border-amber-500/30 bg-slate-900 p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-amber-300">Canonical 1Q local runtime</p><h2 className="mt-1 text-3xl font-bold text-white">ABCD ICO V3</h2><p className="mt-2 text-sm text-slate-300">This read-only surface uses the checkpoint-validated ICOManagerV3 API. Historical ICO V2 and Presale records are unavailable.</p></div><button onClick={() => void load()} disabled={loading} className="rounded-xl border border-slate-700 px-4 py-2 text-xs font-semibold text-slate-100 disabled:opacity-50"><RefreshCw className={`mr-2 inline h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div></header>{!snapshot ? <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5 text-sm text-amber-100"><AlertTriangle className="mr-2 inline h-4 w-4" />{message}</div> : <><div className="grid gap-3 md:grid-cols-3">{[['Lifecycle', snapshot.lifecycle], ['Allocated', amount(snapshot.totalAllocated)], ['Runtime', 'ABCDTokenV2 / ICOManagerV3']].map(([label, value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 break-all font-mono text-sm text-white">{value}</p></div>)}</div><p className="break-all text-xs text-slate-400">Chain {snapshot.manifest.chainId} · deployment {snapshot.manifest.deploymentVersion} · ICO {snapshot.manifest.address} · ABCDTokenV2 {snapshot.manifest.abcdAddress} · checkpoint {snapshot.checkpoint.lastProcessedBlock}</p>{snapshot.buyer ? <div className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><h3 className="text-lg font-bold text-white"><Coins className="mr-2 inline h-5 w-5 text-emerald-300" />Your canonical allocation</h3><div className="mt-4 space-y-2 text-xs text-slate-300"><p>Allocated: <span className="font-mono text-white">{amount(snapshot.buyer.purchase.allocation)}</span></p><p>BNB paid: <span className="font-mono text-white">{bnb(snapshot.buyer.purchase.bnbPaid)}</span></p><p>Total vested: <span className="font-mono text-white">{amount(snapshot.buyer.vestedTotal)}</span></p><p>Claimed: <span className="font-mono text-white">{amount(snapshot.buyer.purchase.claimed)}</span></p><p>Claimable now: <span className="font-mono text-white">{amount(snapshot.buyer.claimableNow)}</span></p><p>Refund status: {snapshot.buyer.purchase.refunded ? 'refunded' : 'not refunded'}</p><p>Eligibility: {snapshot.buyer.eligibility ? 'eligible' : 'not eligible'}</p></div></div> : <p className="rounded-2xl border border-slate-800 bg-slate-900 p-5 text-sm text-slate-400">Connect a wallet to read its canonical ICO V3 allocation.</p>}</>}</section>;
};
export default ICOv2Dashboard;
