import React, { useCallback, useEffect, useState } from 'react';
import { RefreshCcw, ShieldCheck, ShoppingCart } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import { approveTargetedLegionSale, cancelTargetedLegionSale, createTargetedLegionSale, displayLegionABCD, getLegionMarketplaceSnapshot, legionMarketplaceError, settleTargetedLegionSale, type LegionMarketplaceSnapshot, type LegionSale } from '../Services/legionMarketplaceV2';

const empty: LegionMarketplaceSnapshot = { available: false, status: 'UNAVAILABLE', sales: [] };
const same = (left?: string | null, right?: string | null) => Boolean(left && right && left.toLowerCase() === right.toLowerCase());
export const LegionMarketplaceV2Dashboard: React.FC = () => {
  const wallet = useWallet(); const [snapshot, setSnapshot] = useState<LegionMarketplaceSnapshot>(empty); const [tokenId, setTokenId] = useState(''); const [buyer, setBuyer] = useState(''); const [price, setPrice] = useState(''); const [adminRequest, setAdminRequest] = useState(''); const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const refresh = useCallback(async () => { try { setError(''); setSnapshot(await getLegionMarketplaceSnapshot()); } catch (reason) { setSnapshot(empty); setError(legionMarketplaceError(reason)); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (key: string, action: (stage: (message: string, hash?: string) => void) => Promise<{ hash: string; indexed: boolean }>) => { if (busy) return; setBusy(key); setError(''); setNotice('Waiting for MetaMask confirmation'); try { const result = await action((message, hash) => setNotice(hash ? `${message}: ${hash}` : message)); setNotice(result.indexed ? `Confirmed on chain and indexed: ${result.hash}` : `Confirmed on chain — waiting for indexer: ${result.hash}`); await refresh(); } catch (reason) { setError(legionMarketplaceError(reason)); } finally { setBusy(null); } };
  return <section aria-label="Canonical targeted Legion marketplace" className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-violet-500/30 bg-slate-900 p-6 shadow-xl">
    <header className="flex flex-wrap justify-between gap-3 border-b border-slate-800 pb-4"><div><p className="text-xs font-black uppercase tracking-wide text-violet-300">Owner-approved Phase 10B extension · local only</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-black text-white"><ShoppingCart className="h-5 w-5" /> Controlled Legion Settlement</h2><p className="mt-1 text-sm text-slate-400">A seller names one buyer, creates the matching LEG-44 request, then a Legion administrator approves it. Only that buyer can settle exact ABCD and the Legion NFT atomically. Public transfers and approvals stay blocked.</p></div><button onClick={() => void refresh()} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-100"><RefreshCcw className="mr-2 inline h-4 w-4" />Refresh</button></header>
    {snapshot.source && <p className="break-all text-xs text-slate-500">Settlement {snapshot.source.settlementAddress} · Legion {snapshot.source.legionAddress} · ABCD {snapshot.source.abcdAddress} · chain {snapshot.source.chainId} · checkpoint {snapshot.checkpoint || 'pending'}</p>}
    {error && <p className="rounded-xl border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-100">{error}</p>}{notice && <p className="rounded-xl border border-violet-500/40 bg-violet-500/10 p-3 text-sm text-violet-100">{notice}</p>}
    {!snapshot.available && <p className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100">{snapshot.reason || 'The canonical Legion settlement deployment/indexer is unavailable.'}</p>}
    {snapshot.available && <><form className="grid gap-2 rounded-2xl border border-slate-700 bg-slate-950/60 p-4 md:grid-cols-4" onSubmit={(event) => { event.preventDefault(); void run('create', (stage) => createTargetedLegionSale(tokenId, buyer, price, stage)); }}><input aria-label="Legion token ID" value={tokenId} onChange={(event) => setTokenId(event.target.value)} placeholder="Legion token ID" className="field" /><input aria-label="Named buyer" value={buyer} onChange={(event) => setBuyer(event.target.value)} placeholder="Named buyer address" className="field" /><input aria-label="ABCD fixed price" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="Fixed ABCD price" className="field" /><button disabled={Boolean(busy) || !wallet.address} className="rounded-xl bg-violet-600 px-3 py-2 text-xs font-black text-white disabled:opacity-50">Create targeted sale</button></form>
      <form className="flex flex-wrap gap-2 rounded-2xl border border-slate-700 bg-slate-950/60 p-4" onSubmit={(event) => { event.preventDefault(); void run('approve', (stage) => approveTargetedLegionSale(adminRequest, stage)); }}><input aria-label="Legion transfer request ID" value={adminRequest} onChange={(event) => setAdminRequest(event.target.value)} placeholder="Legion admin: request ID" className="field min-w-56 flex-1" /><button disabled={Boolean(busy) || !wallet.address} className="rounded-xl border border-violet-400/60 px-3 py-2 text-xs font-bold text-violet-100 disabled:opacity-50"><ShieldCheck className="mr-1 inline h-4 w-4" />Approve linked LEG-44 request</button></form></>}
    <div className="space-y-3">{snapshot.sales.length === 0 ? <p className="rounded-xl border border-slate-700 p-4 text-sm text-slate-400">No active canonical targeted Legion sales are indexed.</p> : snapshot.sales.map((sale) => <Sale key={sale.saleId} sale={sale} wallet={wallet.address} busy={Boolean(busy)} settle={() => void run(`settle-${sale.saleId}`, (stage) => settleTargetedLegionSale(sale, stage))} cancel={() => void run(`cancel-${sale.saleId}`, (stage) => cancelTargetedLegionSale(sale.saleId, stage))} />)}</div>
  </section>;
};
const Sale = ({ sale, wallet, busy, settle, cancel }: { sale: LegionSale; wallet: string | null; busy: boolean; settle: () => void; cancel: () => void }) => <article className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-700 bg-slate-950/70 p-4"><div className="text-xs text-slate-400"><p className="font-black text-white">Sale #{sale.saleId} · {displayLegionABCD(sale.price)} ABCD</p><p className="mt-1">Lifecycle: {sale.status}</p><p>Legion token #{sale.tokenId} · request #{sale.requestId || 'indexing pending'}</p><p className="break-all">Seller {sale.seller}</p><p className="break-all">Named buyer {sale.buyer}</p>{sale.revalidation !== 'CURRENT' && <p className="mt-1 text-amber-200">Not currently settleable: {sale.revalidationReason || 'on-chain validation is unavailable.'}</p>}</div>{same(wallet, sale.seller) ? <button onClick={cancel} disabled={busy} className="rounded-lg border border-rose-400/60 px-3 py-2 text-xs font-bold text-rose-100 disabled:opacity-50">Cancel sale</button> : <button onClick={settle} disabled={busy || !wallet || !same(wallet, sale.buyer) || sale.revalidation !== 'CURRENT' || sale.status !== 'READY_FOR_SETTLEMENT'} className="rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Approve ABCD if needed & settle</button>}</article>;
