import React, { useCallback, useEffect, useState } from 'react';
import { Loader2, MapPinned, RefreshCcw, Send, ShieldAlert } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import { approveLegionNFTV2Transfer, executeLegionNFTV2Transfer, getLegionNFTV2Snapshot, hasLegionNFTV2AdminCapability, legionNFTV2ErrorMessage, requestLegionNFTV2Transfer, type LegionNFTV2Snapshot, type LegionNFTV2Territory } from '../Services/legionNFTV2';

const empty: LegionNFTV2Snapshot = { available: false, status: 'UNAVAILABLE', paused: false, territories: [], history: {}, requests: {} };
const addressEqual = (left?: string | null, right?: string | null) => Boolean(left && right && left.toLowerCase() === right.toLowerCase());

export const LegionNFTV2Dashboard: React.FC = () => {
  const wallet = useWallet(); const [snapshot, setSnapshot] = useState<LegionNFTV2Snapshot>(empty); const [canApproveTransfers, setCanApproveTransfers] = useState(false); const [loading, setLoading] = useState(false); const [proposed, setProposed] = useState<Record<string, string>>({}); const [busy, setBusy] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { if (!wallet.address) { setSnapshot(empty); setCanApproveTransfers(false); return; } const nextSnapshot = await getLegionNFTV2Snapshot(wallet.address); setSnapshot(nextSnapshot); setCanApproveTransfers(wallet.isCorrectNetwork && nextSnapshot.available ? await hasLegionNFTV2AdminCapability(wallet.address, nextSnapshot) : false); } catch (reason) { setSnapshot(empty); setCanApproveTransfers(false); setError(legionNFTV2ErrorMessage(reason)); } finally { setLoading(false); } }, [wallet.address, wallet.isCorrectNetwork]);
  useEffect(() => { void refresh(); }, [refresh]);
  const action = async (key: string, run: (stage: (message: string, hash?: string) => void) => Promise<{ hash: string }>) => { if (busy) return; setBusy(key); setError(null); setNotice('Waiting for MetaMask confirmation'); try { const result = await run((message, hash) => setNotice(hash ? `${message}: ${hash}` : message)); setNotice(`Confirmed: ${result.hash}. Waiting for indexed reconciliation…`); await refresh(); } catch (reason) { setError(legionNFTV2ErrorMessage(reason)); } finally { setBusy(null); } };
  const source = snapshot.source;
  return <section aria-label="Canonical LegionNFTV2 dashboard" className="mx-auto max-w-5xl space-y-5 rounded-3xl border border-indigo-500/30 bg-slate-900 p-6 shadow-xl">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-800 pb-4"><div><p className="text-xs font-black uppercase tracking-wide text-indigo-300">Canonical Phase 8 registry</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-black text-white"><MapPinned className="h-5 w-5" /> Legion Territories</h2><p className="mt-1 max-w-3xl text-sm text-slate-400">Country → State → District only. Territory records and transfer provenance are indexed from LegionNFTV2; Continent, marketplace, approvals, and financial rights are excluded.</p></div><button onClick={() => void refresh()} disabled={loading} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-100 disabled:opacity-50"><RefreshCcw className={`mr-2 inline h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></header>
    {source && <p className="break-all text-xs text-slate-500">Contract {source.contractAddress} · chain {source.chainId} · indexer checkpoint {snapshot.checkpoint || 'pending'}</p>}
    {snapshot.paused && <Notice kind="warning" text="LegionNFTV2 is paused. All state-changing Legion operations are blocked on-chain." />}
    {error && <Notice kind="error" text={error} />}{notice && <Notice kind={busy ? 'warning' : 'success'} text={notice} />}
    {!wallet.address && <Notice kind="warning" text="Connect a wallet to read its canonical LegionNFTV2 records." />}
    {!wallet.isCorrectNetwork && wallet.address && <Notice kind="error" text="Switch MetaMask to Hardhat Local (31337)." />}
    {snapshot.status === 'UNDEPLOYED' && <Notice kind="warning" text={snapshot.reason || 'LegionNFTV2 is not deployed.'} />}
    {snapshot.status === 'UNAVAILABLE' && wallet.address && <Notice kind="warning" text={snapshot.reason || 'The LegionNFTV2 indexer is not yet available.'} />}
    {snapshot.available && snapshot.territories.length === 0 && <p className="rounded-xl border border-slate-700 bg-slate-950/60 p-5 text-sm text-slate-300">No canonical Country, State, or District NFT is currently indexed for this wallet.</p>}
    {snapshot.territories.map((territory) => { const request = snapshot.requests[territory.tokenId]; const owned = addressEqual(wallet.address, territory.owner); return <article key={territory.tokenId} className="space-y-4 rounded-2xl border border-slate-700 bg-slate-950/70 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{territory.level} · #{territory.tokenId}</p><h3 className="mt-1 text-lg font-black text-white">{territory.displayName}</h3></div><span className="rounded-full border border-indigo-400/40 px-3 py-1 text-xs font-bold text-indigo-200">Registry-controlled transfer only</span></div><dl className="grid gap-3 text-xs sm:grid-cols-2"><Field label="Owner" value={territory.owner} /><Field label="Parent ID" value={territory.parentId === '0' ? 'None (Country root)' : `#${territory.parentId}`} /><Field label="Canonical identifier" value={territory.canonicalIdentifier} /><Field label="Population (informational)" value={territory.population} /><Field label="Metadata URI" value={territory.metadataURI} /><Field label="Territory key" value={territory.territoryKey} /></dl><History events={snapshot.history[territory.tokenId] || []} />{request ? <TransferRequest territory={territory} request={request} connectedWallet={wallet.address} canApproveTransfers={canApproveTransfers} busy={busy} action={action} /> : owned && !snapshot.paused && <div className="border-t border-slate-800 pt-4"><p className="text-sm font-bold text-slate-100">Request controlled transfer</p><p className="mt-1 text-xs text-slate-400">This creates a request only. A Legion administrator must approve it before the current owner can execute the transfer.</p><div className="mt-3 flex flex-wrap gap-2"><input value={proposed[territory.tokenId] || ''} onChange={(event) => setProposed({ ...proposed, [territory.tokenId]: event.target.value })} placeholder="Proposed new operator address" className="field min-w-72 flex-1" /><button disabled={Boolean(busy)} onClick={() => void action(`request-${territory.tokenId}`, (stage) => requestLegionNFTV2Transfer(territory.tokenId, proposed[territory.tokenId] || '', stage))} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50"><Send className="mr-1 inline h-3 w-3" />Request transfer</button></div></div>}</article>; })}
    <aside className="rounded-xl border border-slate-700 bg-slate-950/60 p-4 text-xs text-slate-400">Artwork catalog assets are available for preview only. No artwork is assigned to a territory until an authoritative mapping and production metadata workflow exist.</aside>
  </section>;
};

const TransferRequest = ({ territory, request, connectedWallet, canApproveTransfers, busy, action }: any) => <div className="space-y-3 border-t border-slate-800 pt-4"><p className="text-sm font-bold text-slate-100">Transfer request #{request.requestId}</p><p className="text-xs text-slate-400">Current operator {request.currentOwner} → proposed operator {request.proposedOwner} · {request.approved ? 'Approved' : 'Awaiting administrator approval'}</p><div className="flex flex-wrap gap-2">{!request.approved && canApproveTransfers && <button disabled={Boolean(busy)} onClick={() => void action(`approve-${request.requestId}`, (stage: any) => approveLegionNFTV2Transfer(request.requestId, stage))} className="rounded-lg border border-indigo-400/60 px-3 py-2 text-xs font-bold text-indigo-100 disabled:opacity-50">Approve as administrator</button>}{request.approved && addressEqual(connectedWallet, request.currentOwner) && <button disabled={Boolean(busy)} onClick={() => void action(`execute-${request.requestId}`, (stage: any) => executeLegionNFTV2Transfer(request.requestId, stage))} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Execute approved transfer</button>}</div></div>;
const Field = ({ label, value }: { label: string; value: string }) => <div><dt className="uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all text-slate-200">{value}</dd></div>;
const History = ({ events }: { events: any[] }) => <div className="border-t border-slate-800 pt-3"><p className="text-xs font-black uppercase tracking-wide text-slate-400">On-chain provenance</p>{events.length === 0 ? <p className="mt-2 text-xs text-slate-500">No confirmed indexed event is available yet.</p> : <ol className="mt-2 space-y-1">{events.map((event) => <li key={`${event.transactionHash}:${event.logIndex}`} className="break-all text-xs text-slate-400">{event.eventName} · block {event.blockNumber} · {event.transactionHash}</li>)}</ol>}</div>;
const Notice = ({ kind, text }: { kind: 'error' | 'warning' | 'success'; text: string }) => <div className={`rounded-xl border p-3 text-sm ${kind === 'error' ? 'border-rose-500/40 bg-rose-500/10 text-rose-100' : kind === 'success' ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-100' : 'border-amber-500/40 bg-amber-500/10 text-amber-100'}`}><ShieldAlert className="mr-2 inline h-4 w-4" />{text}</div>;
