import React, { useCallback, useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import { borrowV2, createV2Request, depositV2Collateral, fundV2Request, getV2Loan, lendingV2ErrorMessage, liquidateV2, metadataHashForUri, payV2Emi, repayAllV2, repayV2, V2Read, withdrawV2Collateral } from '../Services/lendingV2';

type Phase = 'idle' | 'wallet' | 'confirming' | 'success' | 'error';
const validAmount = (v: string) => /^\d+(\.\d+)?$/.test(v) && Number(v) > 0;
export const LendingV2: React.FC = () => {
  const { address, isConnected, isCorrectNetwork, refreshBalances } = useWallet();
  const [loanId, setLoanId] = useState(''); const [loan, setLoan] = useState<V2Read | null>(null); const [depositId, setDepositId] = useState('');
  const [collateral, setCollateral] = useState(''); const [principal, setPrincipal] = useState(''); const [repayment, setRepayment] = useState(''); const [term, setTerm] = useState('30');
  const [uri, setUri] = useState(''); const [metadataHash, setMetadataHash] = useState(''); const [requestId, setRequestId] = useState(''); const [phase, setPhase] = useState<Phase>('idle'); const [message, setMessage] = useState<string | null>(null); const [hash, setHash] = useState<string | null>(null);
  const read = useCallback(async () => { if (!loanId) { setLoan(null); return; } try { setLoan(await getV2Loan(loanId)); } catch (error) { setLoan(null); setMessage(lendingV2ErrorMessage(error)); setPhase('error'); } }, [loanId]);
  useEffect(() => { void read(); }, [read]);
  const execute = async (name: string, operation: () => Promise<{ hash: string; blockNumber: string; loanId: string | null; requestId: string | null; depositId: string | null }>) => {
    if (!isConnected || !address) { setPhase('error'); setMessage('Connect MetaMask to use Lending V2.'); return; }
    if (!isCorrectNetwork) { setPhase('error'); setMessage('Switch MetaMask to Hardhat Local (31337).'); return; }
    setPhase('wallet'); setHash(null); setMessage(`Confirm ${name} in MetaMask.`);
    try { const tx = await operation(); setHash(tx.hash); setPhase('success'); setMessage(`${name} confirmed in block ${tx.blockNumber}.${tx.depositId ? ` Pending deposit #${tx.depositId}.` : ''}${tx.loanId ? ` Loan #${tx.loanId}.` : ''}${tx.requestId ? ` Request #${tx.requestId}.` : ''}`); if (tx.depositId) setDepositId(tx.depositId); if (tx.loanId) setLoanId(tx.loanId); if (tx.requestId) setRequestId(tx.requestId); await Promise.all([read(), refreshBalances()]); } catch (error) { setPhase('error'); setMessage(lendingV2ErrorMessage(error)); }
  };
  const busy = phase === 'wallet' || phase === 'confirming';
  const metadataReady = /^0x[a-fA-F0-9]{64}$/.test(metadataHash) && /^(ipfs:\/\/|https?:\/\/).+/.test(uri);
  return <section className="space-y-6" aria-label="Lending V2">
    <header className="rounded-3xl border border-cyan-500/30 bg-slate-900 p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Isolated Lending V2 — local Hardhat only</p><h2 className="mt-1 text-2xl font-black text-white">Loan-scoped collateral, 12% APR & authoritative previews</h2><p className="mt-2 text-sm text-slate-400">V1 remains unchanged. V2 requires a real metadata URI and content hash for every new loan certificate.</p></header>
    {(!isConnected || !isCorrectNetwork) && <Notice kind="error" text={!isConnected ? 'Connect MetaMask to access Lending V2.' : 'Switch MetaMask to Hardhat Local (chain ID 31337).'} />}{message && <Notice kind={phase === 'error' ? 'error' : phase === 'success' ? 'success' : 'pending'} text={message} hash={hash} />}
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><h3 className="font-black text-white">Loan metadata (required, never fabricated)</h3><div className="grid gap-3 md:grid-cols-2"><Field label="Metadata URI (ipfs:// or https://)" value={uri} setValue={setUri} /><Field label="Metadata hash (bytes32)" value={metadataHash} setValue={setMetadataHash} /></div><button onClick={() => setMetadataHash(metadataHashForUri(uri))} disabled={!uri} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-200 disabled:opacity-50">Hash entered URI</button><p className="text-xs text-slate-500">Hashing the URI proves the supplied URI string only. It does not upload metadata. Use the existing authenticated metadata-storage workflow to create content first.</p></section>
    <div className="grid gap-4 lg:grid-cols-2"><Card title="1. Deposit ETH collateral"><Field label="ETH amount" value={collateral} setValue={setCollateral} /><button disabled={busy || !validAmount(collateral)} onClick={() => void execute('Collateral deposit', () => depositV2Collateral(collateral))} className="btn">Deposit collateral</button><p className="hint">The confirmed event returns a deposit ID. Copy it into the borrow form.</p></Card><Card title="2. Borrow ABCD"><Field label="Pending deposit ID" value={depositId} setValue={setDepositId} /><Field label="ABCD principal" value={principal} setValue={setPrincipal} /><Term value={term} setValue={setTerm} /><button disabled={busy || !validAmount(principal) || !depositId || !metadataReady} onClick={() => void execute('Borrow', () => borrowV2(depositId, principal, Number(term), uri, metadataHash))} className="btn">Borrow against deposit</button></Card><Card title="3. Repay ABCD"><Field label="Loan ID" value={loanId} setValue={setLoanId} /><Field label="Partial ABCD amount" value={repayment} setValue={setRepayment} /><div className="flex flex-wrap gap-2"><button disabled={busy || !loanId || !validAmount(repayment)} onClick={() => void execute('Partial repayment', () => repayV2(loanId, repayment))} className="btn">Approve & repay</button><button disabled={busy || !loanId} onClick={() => void execute('Full repayment', () => repayAllV2(loanId))} className="btn-secondary">Approve & repay all</button></div></Card><Card title="4. Withdraw settled collateral"><Field label="Loan ID" value={loanId} setValue={setLoanId} /><button disabled={busy || !loanId} onClick={() => void execute('Collateral withdrawal', () => withdrawV2Collateral(loanId))} className="btn">Withdraw after full settlement</button><p className="hint">The contract rejects this while any debt remains.</p></Card></div>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><h3 className="font-black text-white">P2P V2</h3><div className="grid gap-4 lg:grid-cols-2"><Card title="Create request"><Field label="ABCD principal" value={principal} setValue={setPrincipal} /><Field label="ETH collateral" value={collateral} setValue={setCollateral} /><Term value={term} setValue={setTerm} /><button disabled={busy || !validAmount(principal) || !validAmount(collateral) || !metadataReady} onClick={() => void execute('P2P request', () => createV2Request(principal, collateral, Number(term), uri, metadataHash))} className="btn">Create P2P request</button></Card><Card title="Fund request"><Field label="Request ID" value={requestId} setValue={setRequestId} /><Field label="Request principal ABCD" value={principal} setValue={setPrincipal} /><button disabled={busy || !requestId || !validAmount(principal)} onClick={() => void execute('P2P funding', () => fundV2Request(requestId, principal))} className="btn">Approve & fund</button><Field label="Loan ID for EMI" value={loanId} setValue={setLoanId} /><button disabled={busy || !loanId || !validAmount(repayment)} onClick={() => void execute('EMI payment', () => payV2Emi(loanId, repayment))} className="btn-secondary">Approve & pay next EMI</button></Card></div></section>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div className="flex justify-between gap-3"><div><h3 className="font-black text-white">Authoritative loan state</h3><p className="text-xs text-slate-400">Financial previews come directly from LoanManagerV2/LiquidationV2, never from frontend calculations.</p></div><button onClick={() => void read()} disabled={!loanId || busy} className="btn-secondary inline-flex items-center gap-2"><RefreshCw className="h-4 w-4" />Refresh</button></div>{loan ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Outstanding" value={`${loan.outstanding} ABCD`} /><Metric label="Accrued interest" value={`${loan.accruedInterest} ABCD`} /><Metric label="Late fee" value={`${loan.lateFee} ABCD`} /><Metric label="Current LTV" value={`${loan.ltvBps} bps`} /><Metric label="Health factor" value={loan.healthFactor} /><Metric label="Liquidatable" value={loan.liquidatable ? 'Yes' : 'No'} /><Metric label="Loan state" value={String(loan.state)} /><Metric label="Metadata URI" value={loan.metadata?.uri || 'Unavailable'} /></div> : <p className="text-sm text-slate-500">Enter a real V2 loan ID to read its canonical state.</p>}{loan?.liquidatable && <button disabled={busy} onClick={() => void execute('Liquidation', () => liquidateV2(loanId))} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-bold text-white">Approve & liquidate eligible loan</button>}</section>
  </section>;
};
const Card = ({ title, children }: { title: string; children: React.ReactNode }) => <article className="space-y-3 rounded-2xl border border-slate-800 bg-slate-950 p-4"><h4 className="font-bold text-white">{title}</h4>{children}</article>;
const Field = ({ label, value, setValue }: { label: string; value: string; setValue: (v: string) => void }) => <label className="block text-xs text-slate-400">{label}<input value={value} onChange={(e) => setValue(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /></label>;
const Term = ({ value, setValue }: { value: string; setValue: (value: string) => void }) => <label className="block text-xs text-slate-400">Term<select value={value} onChange={(e) => setValue(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white"><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option></select></label>;
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 break-all font-mono text-xs text-slate-100">{value}</p></div>;
const Notice = ({ kind, text, hash }: { kind: 'error' | 'success' | 'pending'; text: string; hash?: string | null }) => <div className={`rounded-2xl border p-4 text-sm ${kind === 'error' ? 'border-rose-500/30 bg-rose-500/10 text-rose-200' : kind === 'success' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200' : 'border-sky-500/30 bg-sky-500/10 text-sky-100'}`}><div className="flex gap-2"><ShieldCheck className="h-5 w-5 shrink-0" />{text}</div>{hash && <p className="mt-2 break-all font-mono text-xs">{hash}</p>}</div>;
