import React, { useCallback, useEffect, useState } from 'react';
import { formatEther } from 'ethers';
import { Loader2, RefreshCw, ShieldCheck } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import {
  borrowTokens, CanonicalLendingReadState, cancelMarketplaceLoan, createCanonicalLoanRequest, depositCollateral,
  executeLiquidation, fundMarketplaceLoan, getCanonicalLendingReadState, getLendingLiquidationEligibility,
  getFundedLoansForLender, getOpenLoanRequests, LiquidationEligibilityRead, liquidateDefaultedMarketplaceLoan, markMarketplaceLoanDefaulted,
  payLoanEmi, repayLoan, withdrawCollateral,
} from '../Services/lending';

type TxState = 'idle' | 'awaiting-wallet' | 'confirming' | 'success' | 'error';
const positive = (value: string) => /^\d+(?:\.\d+)?$/.test(value) && Number(value) > 0;
const transactionError = (cause: any, fallback: string) => {
  const code = cause?.code ?? cause?.info?.error?.code;
  if (code === 4001 || code === 'ACTION_REJECTED' || /user rejected|user denied/i.test(String(cause?.message))) {
    return 'Transaction rejected in MetaMask. No on-chain state was changed.';
  }
  return cause?.shortMessage || cause?.reason || cause?.info?.error?.message || cause?.message || fallback;
};

export const LendingPool: React.FC = () => {
  const { address, isConnected, isCorrectNetwork, refreshBalances } = useWallet();
  const [data, setData] = useState<CanonicalLendingReadState | null>(null);
  const [openRequests, setOpenRequests] = useState<any[]>([]);
  const [fundedLoans, setFundedLoans] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [txState, setTxState] = useState<TxState>('idle');
  const [message, setMessage] = useState<string | null>(null);
  const [hash, setHash] = useState<string | null>(null);
  const [deposit, setDeposit] = useState(''); const [borrow, setBorrow] = useState('');
  const [repay, setRepay] = useState(''); const [withdraw, setWithdraw] = useState('');
  const [request, setRequest] = useState({ principal: '', collateral: '', rateBps: '925', durationMonths: '3', purpose: 'ABCDeFi loan' });
  const [liquidationBorrower, setLiquidationBorrower] = useState(''); const [liquidationDebt, setLiquidationDebt] = useState('');
  const [liquidation, setLiquidation] = useState<LiquidationEligibilityRead | null>(null);

  const refresh = useCallback(async () => {
    if (!address || !isConnected || !isCorrectNetwork) { setData(null); setOpenRequests([]); setFundedLoans([]); setError(null); return; }
    setLoading(true); setError(null);
    const [stateResult, requestsResult, fundedResult] = await Promise.allSettled([getCanonicalLendingReadState(address), getOpenLoanRequests(), getFundedLoansForLender(address)]);
    if (stateResult.status === 'fulfilled') setData(stateResult.value); else { setData(null); setError(stateResult.reason?.message || 'Unable to read canonical lending state.'); }
    if (requestsResult.status === 'fulfilled') setOpenRequests(requestsResult.value); else setOpenRequests([]);
    if (fundedResult.status === 'fulfilled') setFundedLoans(fundedResult.value); else setFundedLoans([]);
    setLoading(false);
  }, [address, isConnected, isCorrectNetwork]);

  useEffect(() => { void refresh(); }, [refresh]);
  const run = async (label: string, operation: (submitted: (transactionHash: string, step?: string) => void) => Promise<unknown>) => {
    if (txState === 'awaiting-wallet' || txState === 'confirming') return;
    if (!isConnected || !address) { setTxState('error'); setMessage('Connect a wallet before submitting a lending transaction.'); return; }
    if (!isCorrectNetwork) { setTxState('error'); setMessage('Switch to Hardhat Local (chain ID 31337) before submitting a lending transaction.'); return; }
    setHash(null); setError(null); setTxState('awaiting-wallet'); setMessage(`Confirm ${label} in MetaMask.`);
    try {
      await operation((transactionHash, step) => { setHash(transactionHash); setTxState('confirming'); setMessage(`${step || label} submitted. Waiting for on-chain confirmation…`); });
      await Promise.all([refresh(), refreshBalances()]);
      setTxState('success'); setMessage(`${label} confirmed on-chain.`);
    } catch (cause: any) {
      setTxState('error'); setMessage(transactionError(cause, `${label} failed.`));
    }
  };
  const lookupLiquidation = async () => {
    if (!liquidationBorrower) { setError('Enter a borrower wallet address.'); return; }
    try { setError(null); setLiquidation(await getLendingLiquidationEligibility(liquidationBorrower)); }
    catch (cause: any) { setLiquidation(null); setError(cause?.message || 'Unable to read liquidation eligibility.'); }
  };
  const pool = data?.directPool; const busy = txState === 'awaiting-wallet' || txState === 'confirming';

  return <section className="space-y-6" aria-label="Lending">
    <header className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-purple-400">Phase 6B · canonical on-chain lending</p><h2 className="mt-1 text-xl font-black text-white">Lending state & transactions</h2><p className="mt-1 text-xs text-slate-400">Reads use the canonical deployment RPC. Every transaction waits for its confirmed receipt before this state refreshes.</p></div><button onClick={() => void refresh()} disabled={loading || busy || !isConnected || !isCorrectNetwork} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-xs text-slate-200 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div></header>
    {!isConnected && <Notice kind="error" text="Connect a wallet to read or use lending." />}{isConnected && !isCorrectNetwork && <Notice kind="error" text="Switch the connected wallet to Hardhat Local (chain ID 31337)." />}{error && <Notice kind="error" text={error} />}{message && <Notice kind={txState === 'error' ? 'error' : txState === 'success' ? 'success' : 'pending'} text={message} hash={hash} />}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="ABCD wallet balance" value={data ? `${data.abcdBalance} ABCD` : 'Unavailable'} /><Metric label="ETH collateral" value={pool ? `${pool.collateral} ETH` : 'Unavailable'} /><Metric label="ABCD debt" value={pool ? `${pool.borrowed} ABCD` : 'Unavailable'} /><Metric label="Available to borrow" value={pool ? `${pool.availableToBorrow} ABCD` : 'Unavailable'} /><Metric label="Pool liquidity" value={pool ? `${pool.liquidity} ABCD` : 'Unavailable'} /><Metric label="Repayment allowance" value={pool ? `${pool.repaymentAllowance} ABCD` : 'Unavailable'} /><Metric label="LTV limit" value={pool ? `${(pool.ltvBps / 100).toFixed(2)}%` : 'Unavailable'} /><Metric label="Health factor" value={data?.liquidationHealthFactor ?? 'Unavailable'} /></div>

    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">Direct LendingPool</h3><p className="mt-1 text-xs text-slate-400">ETH collateral is held by LendingPool. ABCD repayment approval is requested only when needed.</p></div><div className="grid gap-4 lg:grid-cols-2"><ActionCard title="Deposit ETH collateral" amount={deposit} setAmount={setDeposit} suffix="ETH" button="Deposit" disabled={busy || !positive(deposit) || Boolean(pool?.paused)} onSubmit={() => void run('Collateral deposit', (submitted) => depositCollateral(deposit, submitted))} /><ActionCard title="Borrow ABCD" amount={borrow} setAmount={setBorrow} suffix="ABCD" button="Borrow" disabled={busy || !positive(borrow) || Boolean(pool?.paused)} onSubmit={() => void run('Borrow', (submitted) => borrowTokens(borrow, submitted))} /><ActionCard title="Repay ABCD" amount={repay} setAmount={setRepay} suffix="ABCD" button="Approve & repay" disabled={busy || !positive(repay) || Boolean(pool?.paused)} hint="If allowance is insufficient, MetaMask will request ABCD approval first." onSubmit={() => void run('Repayment', (submitted) => repayLoan(repay, submitted))} /><ActionCard title="Withdraw ETH collateral" amount={withdraw} setAmount={setWithdraw} suffix="ETH" button="Withdraw" disabled={busy || !positive(withdraw) || Boolean(pool?.paused)} onSubmit={() => void run('Collateral withdrawal', (submitted) => withdrawCollateral(withdraw, submitted))} /></div></section>

    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">Create P2P loan request</h3><p className="mt-1 text-xs text-slate-400">The Marketplace forwards ETH collateral to CollateralVault, then creates an on-chain OPEN request. Duration is the contract’s actual months parameter.</p></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><Input label="Principal ABCD" value={request.principal} setValue={(principal) => setRequest({ ...request, principal })} /><Input label="Collateral ETH" value={request.collateral} setValue={(collateral) => setRequest({ ...request, collateral })} /><Input label="Rate (bps)" value={request.rateBps} setValue={(rateBps) => setRequest({ ...request, rateBps })} /><Input label="Months" value={request.durationMonths} setValue={(durationMonths) => setRequest({ ...request, durationMonths })} /><Input label="Purpose" value={request.purpose} setValue={(purpose) => setRequest({ ...request, purpose })} /></div><button disabled={busy || !positive(request.principal) || !positive(request.collateral)} onClick={() => void run('Loan request creation', (submitted) => createCanonicalLoanRequest(request.principal, request.collateral, Number(request.rateBps), Number(request.durationMonths), request.purpose, submitted))} className="rounded-xl bg-indigo-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Create loan request</button></section>

    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">Open P2P requests</h3><p className="mt-1 text-xs text-slate-400">Canonical RequestCreated events are reconciled with current LoanMarketplace request state.</p></div>{!loading && openRequests.length === 0 && <p className="text-sm text-slate-500">No open requests on this deployment.</p>}<div className="grid gap-4 lg:grid-cols-2">{openRequests.map((loan) => <article key={loan.id.toString()} className="rounded-2xl border border-slate-800 bg-slate-950 p-4 space-y-2 text-xs"><div className="flex justify-between gap-3"><b className="text-white">Request #{loan.id.toString()}</b><span className="font-mono text-purple-300">OPEN</span></div><Row label="Borrower" value={loan.borrower} /><Row label="Principal" value={`${formatEther(loan.principalAmount)} ABCD`} /><Row label="Collateral" value={`${formatEther(loan.collateralETH)} ETH`} /><Row label="Interest" value={`${(Number(loan.interestRateBps) / 100).toFixed(2)}%`} /><Row label="Duration" value={`${loan.durationMonths.toString()} months`} /><div className="flex gap-2 pt-2">{address?.toLowerCase() === String(loan.borrower).toLowerCase() ? <button disabled={busy} onClick={() => void run('Loan request cancellation', (submitted) => cancelMarketplaceLoan(loan.id.toString(), submitted))} className="rounded-xl border border-rose-500/40 px-3 py-2 text-xs font-bold text-rose-200 disabled:opacity-50">Cancel request</button> : <button disabled={busy} onClick={() => void run('Loan funding', (submitted) => fundMarketplaceLoan(loan.id.toString(), formatEther(loan.principalAmount), submitted))} className="rounded-xl bg-amber-500 px-3 py-2 text-xs font-bold text-slate-950 disabled:opacity-50">Approve & fund</button>}</div></article>)}</div></section>

    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">My P2P loan history & EMI</h3><p className="mt-1 text-xs text-slate-400">LoanManager, EMIManager, and LoanNFT values are direct on-chain reads.</p></div>{data?.borrowerLoans.length === 0 && <p className="text-sm text-slate-500">No LoanManager records for this wallet.</p>}<div className="grid gap-4 lg:grid-cols-2">{data?.borrowerLoans.map((loan) => <article key={loan.loanId} className="rounded-2xl border border-slate-800 bg-slate-950 p-4 space-y-2 text-xs"><div className="flex justify-between gap-4"><span className="font-bold text-white">Loan #{loan.loanId}</span><span className="font-mono text-purple-300">{loan.status}</span></div><Row label="Principal" value={`${loan.principal} ABCD`} /><Row label="Outstanding" value={`${loan.outstandingAmount} ABCD`} /><Row label="Interest owed" value={`${loan.interestOwed} ABCD`} /><Row label="Next EMI" value={loan.nextInstallmentAmount ? `${loan.nextInstallmentAmount} ABCD` : 'Unavailable'} /><Row label="Default" value={loan.isDefaulted ? 'Eligible to mark' : 'No'} /><div className="flex flex-wrap gap-2 pt-2">{loan.status === 'ACTIVE' && loan.nextInstallmentAmount && !loan.isDefaulted && <button disabled={busy} onClick={() => void run('EMI payment', (submitted) => payLoanEmi(loan.loanId, submitted))} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Approve & pay EMI</button>}{loan.status === 'ACTIVE' && loan.isDefaulted && <button disabled={busy} onClick={() => void run('P2P default marking', (submitted) => markMarketplaceLoanDefaulted(loan.loanId, submitted))} className="rounded-xl border border-amber-500/40 px-3 py-2 text-xs font-bold text-amber-200 disabled:opacity-50">Mark defaulted</button>}{loan.status === 'DEFAULTED' && <button disabled={busy} onClick={() => void run('P2P liquidation', (submitted) => liquidateDefaultedMarketplaceLoan(loan.loanId, submitted))} className="rounded-xl bg-rose-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Liquidate P2P collateral</button>}</div></article>)}</div></section>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">Loans funded by me</h3><p className="mt-1 text-xs text-slate-400">Canonical LoanMarketplace RequestFunded events resolved to current LoanManager records.</p></div>{fundedLoans.length === 0 && <p className="text-sm text-slate-500">No funded loans for this wallet.</p>}<div className="grid gap-4 lg:grid-cols-2">{fundedLoans.map(({ loanId, loan }) => <article key={loanId.toString()} className="rounded-2xl border border-slate-800 bg-slate-950 p-4 space-y-2 text-xs"><div className="flex justify-between gap-4"><span className="font-bold text-white">Loan #{loanId.toString()}</span><span className="font-mono text-purple-300">{['ACTIVE', 'REPAID', 'LIQUIDATED', 'DEFAULTED'][Number(loan.status)] ?? 'UNKNOWN'}</span></div><Row label="Borrower" value={loan.borrower} /><Row label="Principal" value={`${formatEther(loan.principal)} ABCD`} /><Row label="Repaid" value={`${formatEther(loan.totalRepaid)} ABCD`} /><Row label="Collateral" value={`${formatEther(loan.collateralETH)} ETH`} /></article>)}</div></section>

    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">Direct-pool liquidation</h3><p className="mt-1 text-xs text-slate-400">This applies only to an eligible LendingPool position, not P2P Marketplace loans. No liquidation button is enabled until the contract marks the supplied borrower eligible.</p></div><div className="grid gap-3 md:grid-cols-3"><Input label="Borrower address" value={liquidationBorrower} setValue={setLiquidationBorrower} /><Input label="ABCD debt to cover" value={liquidationDebt} setValue={setLiquidationDebt} /><button onClick={() => void lookupLiquidation()} disabled={busy || !liquidationBorrower} className="mt-5 rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-200 disabled:opacity-50">Check eligibility</button></div>{liquidation && <div className="rounded-2xl border border-slate-800 bg-slate-950 p-4 text-xs space-y-2"><Row label="Eligible" value={liquidation.eligible ? 'Yes' : 'No'} /><Row label="Debt" value={`${liquidation.debtAbcd} ABCD`} /><Row label="Health factor" value={liquidation.healthFactor ?? 'Unavailable'} />{liquidation.eligible && <button disabled={busy || !positive(liquidationDebt)} onClick={() => void run('Liquidation', (submitted) => executeLiquidation(liquidation.borrower, liquidationDebt, submitted))} className="rounded-xl bg-rose-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Approve & liquidate</button>}</div>}</section>
  </section>;
};

const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-2xl border border-slate-800 bg-slate-950 p-4"><p className="text-[11px] uppercase text-slate-500">{label}</p><p className="mt-1 break-words font-mono text-sm font-bold text-slate-100">{value}</p></div>;
const Row = ({ label, value }: { label: string; value: string }) => <div className="flex justify-between gap-3 text-slate-400"><span>{label}</span><span className="break-all text-right font-mono text-slate-200">{value}</span></div>;
const Input = ({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) => <label className="text-xs text-slate-400">{label}<input value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" /></label>;
const ActionCard = ({ title, amount, setAmount, suffix, button, disabled, hint, onSubmit }: { title: string; amount: string; setAmount: (value: string) => void; suffix: string; button: string; disabled: boolean; hint?: string; onSubmit: () => void }) => <div className="rounded-2xl border border-slate-800 bg-slate-950 p-4"><h4 className="font-bold text-white">{title}</h4><div className="mt-3 flex gap-2"><input value={amount} onChange={(event) => setAmount(event.target.value)} inputMode="decimal" placeholder={`Amount in ${suffix}`} className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /><button onClick={onSubmit} disabled={disabled} className="rounded-xl bg-indigo-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">{button}</button></div>{hint && <p className="mt-2 text-[11px] text-slate-400">{hint}</p>}</div>;
const Notice = ({ kind, text, hash }: { kind: 'error' | 'success' | 'pending'; text: string; hash?: string | null }) => <div className={`rounded-2xl border p-4 text-sm ${kind === 'error' ? 'border-rose-500/30 bg-rose-500/10 text-rose-200' : kind === 'success' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200' : 'border-sky-500/30 bg-sky-500/10 text-sky-100'}`}><div className="flex gap-2"><ShieldCheck className="h-5 w-5 shrink-0" /><span>{text}</span></div>{hash && <p className="mt-2 break-all font-mono text-xs">Transaction hash: {hash}</p>}</div>;

export default LendingPool;
