import React, { useCallback, useEffect, useState } from 'react';
import { RefreshCw, ShieldCheck } from 'lucide-react';
import { useWallet } from '../Context/WalletContext';
import { getLendingV2Contracts } from '../Config/contracts';
import {
  borrowV2, createV2Request, depositV2Collateral, fundV2Request, getV2Loan, getV2PendingDeposit, getV2ProtocolState, getV2Request, getV2WalletHistory,
  lendingV2ErrorMessage, liquidateV2, metadataHashForUri, payV2Emi, payV2OutstandingEmi, repayAllV2, repayV2, settleV2Default, stateLabel, V2PendingDeposit, V2ProtocolState, V2Read, V2Request, V2Tx, V2WalletHistory, withdrawV2Collateral,
} from '../Services/lendingV2';

type Phase = 'idle' | 'wallet' | 'success' | 'error';
const validAmount = (value: string) => /^\d+(\.\d+)?$/.test(value) && Number(value) > 0;
const validId = (value: string) => /^\d+$/.test(value) && Number(value) > 0;
const dateValue = (seconds: string) => Number(seconds) > 0 ? new Date(Number(seconds) * 1000).toLocaleString() : 'Not available';

export const LendingV2: React.FC = () => {
  const { address, isConnected, isCorrectNetwork, refreshBalances } = useWallet();
  const v2Available = Boolean(getLendingV2Contracts());
  const [loanId, setLoanId] = useState(''); const [loan, setLoan] = useState<V2Read | null>(null); const [depositId, setDepositId] = useState('');
  const [deposit, setDeposit] = useState<V2PendingDeposit | null>(null); const [request, setRequest] = useState<V2Request | null>(null); const [history, setHistory] = useState<V2WalletHistory | null>(null);
  const [protocol, setProtocol] = useState<V2ProtocolState | null>(null);
  const [collateral, setCollateral] = useState(''); const [principal, setPrincipal] = useState(''); const [repayment, setRepayment] = useState(''); const [term, setTerm] = useState('30');
  const [uri, setUri] = useState(''); const [metadataHash, setMetadataHash] = useState(''); const [requestId, setRequestId] = useState(''); const [phase, setPhase] = useState<Phase>('idle'); const [message, setMessage] = useState<string | null>(null); const [hash, setHash] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    if (!v2Available) return;
    const tasks: Promise<void>[] = [getV2ProtocolState().then(setProtocol)];
    if (validId(loanId)) tasks.push(getV2Loan(loanId).then(setLoan)); else setLoan(null);
    if (validId(depositId)) tasks.push(getV2PendingDeposit(depositId).then(setDeposit)); else setDeposit(null);
    if (validId(requestId)) tasks.push(getV2Request(requestId).then(setRequest)); else setRequest(null);
    if (address) tasks.push(getV2WalletHistory(address).then(setHistory)); else setHistory(null);
    try { await Promise.all(tasks); } catch (error) { setMessage(lendingV2ErrorMessage(error)); setPhase('error'); }
  }, [address, depositId, loanId, requestId, v2Available]);
  useEffect(() => { void refresh(); }, [refresh]);

  if (!v2Available) return <section className="space-y-6" aria-label="Lending V2 unavailable">
    <header className="rounded-3xl border border-cyan-500/30 bg-slate-900 p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Isolated Lending V2 — local Hardhat only</p><h2 className="mt-1 text-2xl font-black text-white">Lending V2 is not deployed in this canonical manifest</h2><p className="mt-2 text-sm text-slate-400">This is a truthful availability state: the active V1 deployment remains usable, but no lendingV2 contract namespace is present in deployments.json.</p></header>
    <Notice kind="error" text="Not available on the current canonical deployment. Deploy the isolated Lending V2 namespace before using V2 reads or transactions." />
  </section>;

  const execute = async (name: string, operation: () => Promise<V2Tx>) => {
    if (!isConnected || !address) { setPhase('error'); setMessage('Connect MetaMask to use Lending V2.'); return; }
    if (!isCorrectNetwork) { setPhase('error'); setMessage('Switch MetaMask to Hardhat Local (31337).'); return; }
    setPhase('wallet'); setHash(null); setMessage(`Confirm ${name} in MetaMask.`);
    try {
      const tx = await operation(); setHash(tx.hash); setPhase('success');
      setMessage(`${name} confirmed in block ${tx.blockNumber}.${tx.approvalHashes.length ? ` ABCD approval confirmed: ${tx.approvalHashes.join(', ')}.` : ''}${tx.depositId ? ` Pending deposit #${tx.depositId}.` : ''}${tx.loanId ? ` Loan #${tx.loanId}.` : ''}${tx.requestId ? ` Request #${tx.requestId}.` : ''}`);
      if (tx.depositId) setDepositId(tx.depositId); if (tx.loanId) setLoanId(tx.loanId); if (tx.requestId) setRequestId(tx.requestId);
      const affectedReads: Promise<unknown>[] = [refreshBalances(), getV2ProtocolState().then(setProtocol)];
      if (tx.depositId) affectedReads.push(getV2PendingDeposit(tx.depositId).then(setDeposit));
      if (tx.loanId) affectedReads.push(getV2Loan(tx.loanId).then(setLoan));
      if (tx.requestId) affectedReads.push(getV2Request(tx.requestId).then(setRequest));
      if (address) affectedReads.push(getV2WalletHistory(address).then(setHistory));
      await Promise.all(affectedReads);
    } catch (error) { setPhase('error'); setMessage(lendingV2ErrorMessage(error)); }
  };
  const busy = phase === 'wallet';
  const metadataReady = /^0x[a-fA-F0-9]{64}$/.test(metadataHash) && /^(ipfs:\/\/|https:\/\/).+/.test(uri);

  return <section className="space-y-6" aria-label="Lending V2">
    <header className="rounded-3xl border border-cyan-500/30 bg-slate-900 p-6"><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Isolated Lending V2 — local Hardhat only</p><h2 className="mt-1 text-2xl font-black text-white">Loan-scoped collateral, 12% APR & authoritative previews</h2><p className="mt-2 text-sm text-slate-400">V1 remains unchanged. V2 uses the current canonical lendingV2 manifest addresses and requires real metadata for each new certificate.</p></header>
    {(!isConnected || !isCorrectNetwork) && <Notice kind="error" text={!isConnected ? 'Connect MetaMask to access Lending V2.' : 'Switch MetaMask to Hardhat Local (chain ID 31337).'} />}{message && <Notice kind={phase === 'error' ? 'error' : phase === 'success' ? 'success' : 'pending'} text={message} hash={hash} />}
    <section className="rounded-3xl border border-cyan-500/30 bg-slate-900 p-6 space-y-4"><div><h3 className="font-black text-white">Deployed V2 protocol state</h3><p className="mt-1 text-xs text-slate-400">Pool, reserve, oracle prices, and risk constants are live contract reads. Terms and grace period are identified from the signed canonical deployment configuration because V2 exposes no getter for those source-level constants.</p></div>{protocol ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="LTV limit" value={`${(Number(protocol.initialLtvBps) / 100).toFixed(2)}%`} /><Metric label="Fixed APR" value={`${(Number(protocol.aprBps) / 100).toFixed(2)}%`} /><Metric label="Liquidation threshold" value={`${(Number(protocol.liquidationThresholdBps) / 100).toFixed(2)}%`} /><Metric label="Close factor" value={`${(Number(protocol.closeFactorBps) / 100).toFixed(2)}%`} /><Metric label="Liquidation bonus" value={`${(Number(protocol.liquidationBonusBps) / 100).toFixed(2)}%`} /><Metric label="Late fee" value={`${(Number(protocol.lateFeeBps) / 100).toFixed(2)}%`} /><Metric label="Terms" value={protocol.supportedTermsDays ? `${protocol.supportedTermsDays.join(' / ')} days` : 'Unavailable'} /><Metric label="Grace period" value={protocol.gracePeriodDays ? `${protocol.gracePeriodDays} days` : 'Unavailable'} /><Metric label="V2 pool liquidity" value={`${protocol.poolLiquidity} ABCD`} /><Metric label="V2 pool ABCD balance" value={`${protocol.poolTokenBalance} ABCD`} /><Metric label="Insurance reserve" value={`${protocol.reserveBalance} ABCD`} /><Metric label="Local oracle prices" value={`ETH $${protocol.ethUsd}; ABCD $${protocol.abcdUsd}`} /></div> : <p className="text-sm text-slate-500">Reading the canonical Lending V2 deployment…</p>}</section>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><h3 className="font-black text-white">Loan metadata (required, never fabricated)</h3><div className="grid gap-3 md:grid-cols-2"><Field label="Metadata URI (ipfs:// or https://)" value={uri} setValue={setUri} /><Field label="Metadata hash (bytes32)" value={metadataHash} setValue={setMetadataHash} /></div><button onClick={() => setMetadataHash(metadataHashForUri(uri))} disabled={!uri} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-200 disabled:opacity-50">Hash entered URI</button><p className="text-xs text-slate-500">This hashes the URI string only; it does not upload metadata. Use the existing authenticated metadata-storage workflow first.</p></section>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card title="1. Deposit ETH collateral"><Field label="ETH amount" value={collateral} setValue={setCollateral} /><button disabled={busy || !validAmount(collateral)} onClick={() => void execute('Collateral deposit', () => depositV2Collateral(collateral))} className="btn">Deposit collateral</button><p className="hint">The confirmed event returns the pending deposit ID used by the borrow step.</p></Card>
      <Card title="2. Preview and borrow ABCD"><Field label="Pending deposit ID" value={depositId} setValue={setDepositId} /><button disabled={busy || !validId(depositId)} onClick={() => void refresh()} className="btn-secondary">Read on-chain borrow capacity</button>{deposit && <div className="grid grid-cols-2 gap-2"><Metric label="Collateral" value={`${deposit.collateralETH} ETH`} /><Metric label="Max borrow (50% LTV)" value={`${deposit.maxBorrowable} ABCD`} /><Metric label="Borrower" value={deposit.borrower} /><Metric label="Active" value={deposit.active ? 'Yes' : 'No'} /></div>}<Field label="ABCD principal" value={principal} setValue={setPrincipal} /><Term value={term} setValue={setTerm} /><button disabled={busy || !validAmount(principal) || !validId(depositId) || !metadataReady} onClick={() => void execute('Borrow', () => borrowV2(depositId, principal, Number(term), uri, metadataHash))} className="btn">Borrow against deposit</button></Card>
      <Card title="3. Repay ABCD"><Field label="Loan ID" value={loanId} setValue={setLoanId} /><Field label="Partial ABCD amount" value={repayment} setValue={setRepayment} /><div className="flex flex-wrap gap-2"><button disabled={busy || !validId(loanId) || !validAmount(repayment)} onClick={() => void execute('Partial repayment', () => repayV2(loanId, repayment))} className="btn">Approve & repay</button><button disabled={busy || !validId(loanId)} onClick={() => void execute('Full repayment', () => repayAllV2(loanId))} className="btn-secondary">Approve & repay all</button></div></Card>
      <Card title="4. Withdraw settled collateral"><Field label="Loan ID" value={loanId} setValue={setLoanId} /><button disabled={busy || !validId(loanId)} onClick={() => void execute('Collateral withdrawal', () => withdrawV2Collateral(loanId))} className="btn">Withdraw after full settlement</button><p className="hint">The V2 contract rejects this while debt remains.</p></Card>
    </div>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><h3 className="font-black text-white">P2P V2</h3><div className="grid gap-4 lg:grid-cols-2">
      <Card title="Create request"><Field label="ABCD principal" value={principal} setValue={setPrincipal} /><Field label="ETH collateral" value={collateral} setValue={setCollateral} /><Term value={term} setValue={setTerm} /><button disabled={busy || !validAmount(principal) || !validAmount(collateral) || !metadataReady} onClick={() => void execute('P2P request', () => createV2Request(principal, collateral, Number(term), uri, metadataHash))} className="btn">Create P2P request</button></Card>
      <Card title="Fund, repay, or settle"><Field label="Request ID" value={requestId} setValue={setRequestId} /><button disabled={busy || !validId(requestId)} onClick={() => void refresh()} className="btn-secondary">Read request</button>{request && <div className="grid grid-cols-2 gap-2"><Metric label="Principal" value={`${request.principal} ABCD`} /><Metric label="Collateral" value={`${request.collateralETH} ETH`} /><Metric label="Status" value={['Open', 'Funded', 'Cancelled', 'Settled'][request.state] || `Unknown (${request.state})`} /><Metric label="Funded loan" value={request.loanId === '0' ? 'Not funded' : `#${request.loanId}`} /></div>}<button disabled={busy || !validId(requestId)} onClick={() => void execute('P2P funding', () => fundV2Request(requestId))} className="btn">Approve & fund request</button><Field label="Loan ID for next EMI" value={loanId} setValue={setLoanId} /><button disabled={busy || !validId(loanId)} onClick={() => void execute('EMI payment', () => payV2Emi(loanId))} className="btn-secondary">Approve & pay next scheduled EMI</button><Field label="Outstanding ABCD after scheduled EMI (if any)" value={repayment} setValue={setRepayment} /><button disabled={busy || !validId(loanId) || !validAmount(repayment)} onClick={() => void execute('Outstanding EMI repayment', () => payV2OutstandingEmi(loanId, repayment))} className="btn-secondary">Approve & settle outstanding EMI</button><p className="hint">Read the authoritative outstanding amount above. A payment mined after maturity may include the contract's one-time late fee.</p><button disabled={busy || !validId(requestId)} onClick={() => void execute('P2P default settlement', () => settleV2Default(requestId))} className="rounded-xl border border-amber-400/50 px-4 py-2 text-xs font-bold text-amber-200 disabled:opacity-50">Settle eligible default</button></Card>
    </div></section>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-4"><div className="flex justify-between gap-3"><div><h3 className="font-black text-white">Authoritative loan state</h3><p className="text-xs text-slate-400">Financial values come from LoanManagerV2, LiquidationV2, EMIManagerV2 and LoanNFTV2—not frontend calculations.</p></div><button onClick={() => void refresh()} disabled={busy} className="btn-secondary inline-flex items-center gap-2"><RefreshCw className="h-4 w-4" />Refresh</button></div>{loan ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Principal" value={`${loan.principal} ABCD`} /><Metric label="Collateral" value={`${loan.collateralETH} ETH`} /><Metric label="Outstanding" value={`${loan.outstanding} ABCD`} /><Metric label="Accrued interest" value={`${loan.accruedInterest} ABCD`} /><Metric label="Late fee" value={`${loan.lateFee} ABCD`} /><Metric label="Total repayment" value={`${loan.totalRepayment} ABCD`} /><Metric label="Maturity" value={dateValue(loan.maturity)} /><Metric label="Loan state" value={stateLabel(loan.state)} /><Metric label="Current LTV" value={`${loan.ltvBps} bps`} /><Metric label="Health factor" value={loan.healthFactor} /><Metric label="Liquidatable" value={loan.liquidatable ? 'Yes' : 'No'} /><Metric label="Borrower" value={loan.borrower} /><Metric label="Lender" value={loan.lender} /><Metric label="LoanNFT" value={loan.metadata ? `#${loan.metadata.tokenId} — ${loan.metadata.owner}` : 'Unavailable'} /><Metric label="Certificate loan" value={loan.metadata ? `#${loan.metadata.loanId}` : 'Unavailable'} /><Metric label="Metadata URI" value={loan.metadata?.uri || 'Unavailable'} /><Metric label="Metadata hash" value={loan.metadata?.hash || 'Unavailable'} /></div>{loan.schedule && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="EMI amount" value={`${loan.schedule.installmentAmount} ABCD`} /><Metric label="EMI paid" value={`${loan.schedule.paidInstallments}/${loan.schedule.installmentCount}`} /><Metric label="Next EMI due" value={dateValue(loan.schedule.nextDueAt)} /><Metric label="EMI completed" value={loan.schedule.completed ? 'Yes' : 'No'} /></div>}{loan.liquidatable && <button disabled={busy} onClick={() => void execute('Liquidation', () => liquidateV2(loanId))} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-bold text-white">Approve & liquidate eligible loan</button>}</> : <p className="text-sm text-slate-500">Enter a real V2 loan ID to read canonical state.</p>}</section>
    <section className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><h3 className="font-black text-white">Confirmed V2 wallet/indexer history</h3><p className="mt-1 text-xs text-slate-400">Source: isolated canonical V2 event projection. It never mixes V1 events.</p>{history ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Direct positions" value={String(history.directPositions.length)} /><Metric label="Loans" value={String(history.loans.length)} /><Metric label="P2P requests" value={String(history.requests.length)} /><Metric label="Indexed events" value={String(history.events.length)} /></div> : <p className="mt-3 text-sm text-slate-500">Connect a wallet and start the V2 indexer to view confirmed history.</p>}</section>
  </section>;
};
const Card = ({ title, children }: { title: string; children: React.ReactNode }) => <article className="space-y-3 rounded-2xl border border-slate-800 bg-slate-950 p-4"><h4 className="font-bold text-white">{title}</h4>{children}</article>;
const Field = ({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) => <label className="block text-xs text-slate-400">{label}<input value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white" /></label>;
const Term = ({ value, setValue }: { value: string; setValue: (value: string) => void }) => <label className="block text-xs text-slate-400">Term<select value={value} onChange={(event) => setValue(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-white"><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option></select></label>;
const Metric = ({ label, value }: { label: string; value: string }) => <div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 break-all font-mono text-xs text-slate-100">{value}</p></div>;
const Notice = ({ kind, text, hash }: { kind: 'error' | 'success' | 'pending'; text: string; hash?: string | null }) => <div className={`rounded-2xl border p-4 text-sm ${kind === 'error' ? 'border-rose-500/30 bg-rose-500/10 text-rose-200' : kind === 'success' ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200' : 'border-sky-500/30 bg-sky-500/10 text-sky-100'}`}><div className="flex gap-2"><ShieldCheck className="h-5 w-5 shrink-0" />{text}</div>{hash && <p className="mt-2 break-all font-mono text-xs">{hash}</p>}</div>;
